Repository mapbox/mapbox-maps-android, pull requests merged in 2021-02, with the labels that each got.

#47 [Annotation plugin] Make getting annotation manager configurable.
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/FillManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/LineManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/SymbolManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnnotationUtils.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/FillActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/LineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/Assets.kt
  app/src/main/res/layout/activity_annotation.xml
  app/src/main/res/menu/menu_symbol.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/QueryAnnotationCallback.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Circle.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Fill.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Line.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/ShadowLogger.java
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationConfig.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
Labels: bug :beetle:, feature :green_apple:

#64 [location-component] Add tests for animators
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt
  app/src/main/res/layout/activity_location_component_amimation.xml
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/Evaluators.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimator.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/EvaluatorsTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckBearingAnimatorTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPositionAnimatorTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimatorTest.kt
Labels: testing :100:

#67 [Annotation plugin] Add bitmap API for Symbol
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Circle.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Fill.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Line.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
Labels: feature :green_apple:

#70 [camera-animation] Fix using camera animation extension functions
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
Labels: bug :beetle:

#74 [location-component] Add tests to improve code coverage.
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/utils/BitmapUtils.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
Labels: testing :100:

#66 [app] Add multi display activity to showcase launching a simple map on a secondary display.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/FragmentBackStackActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MultiDisplayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SecondaryDisplayActivity.kt
  app/src/main/res/layout/activity_debug.xml
  app/src/main/res/layout/activity_empty_fab.xml
  app/src/main/res/layout/activity_multi_display.xml
  app/src/main/res/layout/activity_secondary_display.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
Labels: skip changelog

#76 [Annotation plugin] Add colorInt API for annotation options
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/FillActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/LineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
Labels: feature :green_apple:

#78 [ci] Add CI validation for the generated code.
  .circleci/config.yml
  scripts/ci-circleci-start-pipeline.py
Labels: build, skip changelog

#75 Revisit MapboxMap plugin related extension functions to not use singletons
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapPluginExtensionsDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPlugin.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#77 [sdk] Use cached resourceOptions if it's initialized.
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMapOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxOptions.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapOptionsTest.kt
Labels: bug :beetle:

#80 [rendering] Expose setting FPS listener
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/res/layout/activity_debug.xml
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/OnFpsChangedListener.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: breaking change :warning:, feature :green_apple:

#81 [config] Make xml attribute parsers internal.
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionAttributeParser.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassAttributeParser.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoAttributeParser.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParser.kt
Labels: skip changelog

#84 [Doc] Update the download link for sdk
  DEVELOPING.md
Labels: docs :scroll:, skip changelog

#86 [doc] Fix code snippet to download unstripped binary.
  DEVELOPING.md
Labels: skip changelog

#85 Add example activity of creating MapView
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  app/src/main/res/layout/activity_map_view_customization.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  sdk/src/main/res-public/values/public.xml
  sdk/src/main/res/values/attrs.xml
Labels: feature :green_apple:

#88 Allow StyleManagerInterface.getSourceAs return null
  app/src/main/java/com/mapbox/maps/testapp/examples/AnimatedImageSourceActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/IconSizeChangeOnClickActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/ImageSourceActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
Labels: bug :beetle:

#89 [examples] Fix InsetMapActivity example
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/res/layout/activity_inset_map.xml
Labels: bug :beetle:

#91 [docs] update changelog for v10.0.0-beta.13
  CHANGELOG.md
Labels: docs :scroll:, skip changelog

#105 [annotation] Rename getAnnotationManager to createAnnotationManager.
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/FillManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/LineManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/SymbolManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/FillActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/LineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
Labels: breaking change :warning:

#90 [ktx] Add kotlin dsl builder for CameraOptions and java builders for CameraAnimatorOptions and MapAnimationOptions.
  app/src/main/java/com/mapbox/maps/testapp/examples/AnimateMapCameraActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/CameraPredefinedAnimatorsActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LowLevelCameraAnimatorActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MovingIconWithTrailingLineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MultiDisplayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SecondaryDisplayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SpaceStationLocationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/TextureViewAnimateActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt
  app/src/main/res/values/interpolators.xml
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraAnimatorCoordinator.kt
  sdk-base/src/main/java/com/mapbox/maps/dsl/CameraOptionsKtx.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/MapAnimationOptions.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: breaking change :warning:

#113 [build] Add merge strategies for test app's description and manifest xml.
  .circleci/config.yml
  .gitattributes
Labels: skip changelog

#111 [Annotation plugin] Change the default value of textFont to null; Add size check for properties in Symbol
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
Labels: bug :beetle:

#116 [Compass plugin] Hidden the compass if facing north; apply the opacity correctly.
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
Labels: bug :beetle:

#115 [Annotation plugin] Show all icons and texts of symbols by default
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
Labels: feature :green_apple:

#79 [Annotation plugin] Add GeoJsonOptions to allow to configure the underlying used GeoJsonSource
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationConfig.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationSourceOptions.kt
Labels: feature :green_apple:

#118 [Annotation plugin] Avoid adding same image multi times
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
Labels: bug :beetle:

#123 [style-extension] Rename reference to style plugin and converting them to style extension.
  app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapDelegateProviderTest.kt
Labels: docs :scroll:

#121 [Annotation plugin] Change annotations from map to list
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
Labels: breaking change :warning:

#124 [snapshotter] Introduce interfaces for style events and snapshot result
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt
  sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
  sdk/src/main/java/com/mapbox/maps/CustomSnapshotInterface.kt
  sdk/src/main/java/com/mapbox/maps/SnapshotCreatedListener.kt
  sdk/src/main/java/com/mapbox/maps/SnapshotStyleListener.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
Labels: breaking change :warning:, feature :green_apple:

#99 [location-component] Add isLocatedAt API to location component plugin.
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/PuckLocatedAtPointListener.kt
Labels: feature :green_apple:

#125 [animation] Trigger map camera change updates immediately
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapObserver.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapObserverTest.kt
Labels: bug :beetle:
