Repository mapbox/mapbox-maps-android, pull requests merged in 2021-05, with the labels that each got.

#304 [sdk] Bump to core v10.0.0-beta.21
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureActivityTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/observable/ObservableExtensionTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/overlay/MapOverlayPluginTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MovingIconWithTrailingLineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OrnamentMarginActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/RestrictBoundsActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt
  plugin-overlay/src/test/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginTest.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapCameraPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapTransformDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapAttributionDelegateImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
  sdk/src/test/java/com/mapbox/maps/attribution/MapAttributionDelegateImplTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapPluginRegistryTest.kt
Labels: breaking change :warning:

#305 [docs] cleanup kdoc documentation, remove html tags
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/BaseIntegrationTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/types/FormatSection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/CustomGeometrySource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/ClusterOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: docs :scroll:, skip changelog

#310 Fix crash if doing setCamera during map loading
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapCameraPlugin.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
Labels: bug :beetle:

#311 Update changelog for beta.19
  CHANGELOG.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#313 Update UpdateAnnotationTest to make it more robust
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
Labels: skip changelog

#317 Add an option to mutate camera state using the CameraOptionsKtx.kt DSL
  sdk-base/build.gradle.kts
  sdk-base/src/main/java/com/mapbox/maps/dsl/CameraOptionsKtx.kt
  sdk-base/src/test/java/com/mapbox/maps/dsl/CameraOptionsKtxTest.kt
Labels: feature :green_apple:

#319 Add API for disabling vertical/horizontal scroll gestures
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
  app/src/main/res/layout/generated_test_gestures.xml
  app/src/main/res/menu/menu_gestures.xml
  app/src/main/res/values/strings.xml
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt
  plugin-gestures/src/main/res-public/values/public.xml
  plugin-gestures/src/main/res/values/attrs.xml
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
Labels: feature :green_apple:

#326 Add render cache API
  sdk/src/androidTest/java/com/mapbox/maps/RenderCacheTest.kt
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/RenderCache.kt
Labels: feature :green_apple:

#331 Fix scalebar doesn't update issue.
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
Labels: bug :beetle:

#330 Add removeAnnotationManager API; Fix crash if the belowLayerId doesn't exist on the current style
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolyfillAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolylineAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
Labels: bug :beetle:, feature :green_apple:

#335 [animation] Trigger nested high-level animator listener correctly
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
Labels: bug :beetle:

#322 [compass] make compassview visible when enabled
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
Labels: bug :beetle:

#337 [deps] update telemetry and core dependencies to latest major release
  buildSrc/src/main/kotlin/Project.kt
Labels: breaking change :warning:

#338 Bump gl-native to v10.0.0-beta.22 and common to v12.0.0
  LICENSE.md
  app/src/main/java/com/mapbox/maps/testapp/examples/CacheManagementActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/GeojsonSourceExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/utils/ExpectedUtils.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/ShadowValueConverter.java
  extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/image/ImagePluginImplTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/CustomGeometrySourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/GeoJsonSourceExtTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/ImageSourceExtTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/ImageSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/ShadowValueConverter.java
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/common/ShadowValueConverter.java
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapperTest.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleInterface.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Response.kt
  sdk/src/test/java/com/mapbox/common/ShadowValueConverter.java
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt
Labels: breaking change :warning:

#340 Make MapboxRenderThreadTest robust.
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: skip changelog

#333 Auto active LocationComponent while style loaded.
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: bug :beetle:

#339 Introduce ResourceOptionsManager to configure default resource options, remove xml config for paths.
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  sdk/src/main/java/com/mapbox/maps/CredentialsManager.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
  sdk/src/main/java/com/mapbox/maps/ResourceOptionsManager.kt
  sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
  sdk/src/main/res-public/values/public.xml
  sdk/src/main/res/values/attrs.xml
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt
Labels: breaking change :warning:

#314 [sdk] rename ambient cache database to ambient_cache.db
  .circleci/config.yml
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt
Labels: breaking change :warning:

#345 [examples] Update titles and descriptions for high-priority examples
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#346 [docs] Replace the unsupported character with word
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/LightPosition.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
Labels: docs :scroll:, skip changelog

#349 Restore the default resource options when exiting the MapViewCustomizationActivity.
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
Labels: skip changelog

#351 Update changelog for beta.20
  CHANGELOG.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#355 Adjust changelog for v10.0.0-beta.20
  CHANGELOG.md
Labels: skip changelog

#356 Better changelog entries for v10.0.0-beta.20
  CHANGELOG.md
Labels: skip changelog

#350 [build] cleanup npm used dependencies
  package-lock.json
  package.json
Labels: skip changelog

#358 Avoid clearing styleLoadedListeners inside mapLoadingErrorListener, and vice versa.
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/events/StyleLoadedEventTest.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
Labels: bug :beetle:

#360 Fix usability of DebugModeActivity.
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/res/layout/activity_debug.xml
  app/src/main/res/menu/menu_debug_mode.xml
  app/src/main/res/values/strings.xml
Labels: skip changelog

#362 Bump glNative to 10.0.0-beta.23, common to 13.0.0
  buildSrc/src/main/kotlin/Project.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/CustomGeometrySourceTest.kt
Labels: breaking change :warning:

#352 Make sure to execute first camera update
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: bug :beetle:

#371 Align load style functions for MapboxMap and Snapshotter
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/events/StyleLoadedEventTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/TransparentBackgroundActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Labels: breaking change :warning:

#370 [deps] update telemetry 4.0.2 and android core 7.0.3
  buildSrc/src/main/kotlin/Project.kt
Labels: feature :green_apple:

#373 Change default ambient cache path to .mabox/maps/ambient_cache.db
  sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt
Labels: breaking change :warning:

#375 Move text-font property from PointAnnotation to PointAnnotationManager
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
Labels: breaking change :warning:

#365 Fix crash due to missing access token; delete CredentialsManager.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  sdk/src/main/java/com/mapbox/maps/CredentialsManager.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/ResourceOptionsManager.kt
  sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
  sdk/src/test/java/com/mapbox/maps/CredentialsManagerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt
Labels: bug :beetle:

#377 Call style loaded callback if data set directly to geojson
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
Labels: bug :beetle:
