Repository mapbox/mapbox-maps-android, pull requests merged in 2021-12, with the labels that each got.

#929 Add missing changelog entry for v10.2.0-beta.1
  CHANGELOG.md
Labels: skip changelog

#927 [gestures] Fix gestures at high camera pitch near horizon line.
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: bug :beetle:

#936 Update the java doc in plugin settings to clarify the margin properties are in pixel
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettings.kt
Labels: skip changelog

#939 port dependencies bump
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#940 Add changelog for v10.2.0-rc.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#950 Remove section about release management
  DEVELOPING.md
Labels: skip changelog

#932 Add startDelay property for MapAnimationOptions.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/MapAnimationOptions.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: feature :green_apple:

#951 Port changelog for v10.2.0-rc.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#937 bump gl-native to v10.2.0, common to v21.0.0
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#955 Add patch recall notices to changelog.
  CHANGELOG.md
Labels: skip changelog

#956 Add patch recall notices to changelog.
  CHANGELOG.md
Labels: skip changelog

#961 [testapp] Update raw expression example to use style extension.
  app/src/main/java/com/mapbox/maps/testapp/examples/RawExpressionActivity.kt
Labels: skip changelog

#952 Deprecate map extension function to get gesture settings
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
Labels: feature :green_apple:

#963 Add token shield instruction and pre-commit scripts.
  DEVELOPING.md
  scripts/install-pre-commit/install-pre-commit.sh
  scripts/install-pre-commit/pre-commit.sh
Labels: operations

#967 Remove carbon from our docs.
  module-telemetry/gradle.properties
  plugin-annotation/gradle.properties
  plugin-attribution/gradle.properties
  plugin-compass/gradle.properties
  scripts/update-android-docs.sh
  sdk-base/gradle.properties
  sdk/gradle.properties
Labels: skip changelog, docs :scroll:

#964 Introduce Mapbox exceptions instead of runtime
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/NinePatchUtils.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/PromoteId.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/utils/ExpectedUtils.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationOptions.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
  sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProjectionUtils.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
Labels: feature :green_apple:

#966 Fix empty snapshot on certain devices
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: bug :beetle:

#960 Add tile requests delay apis
  app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
  app/src/main/res/menu/menu_tilejson.xml
  app/src/main/res/values/strings.xml
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
Labels: feature :green_apple:

#974 Remove API to remove light
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
Labels: skip changelog

#978 patch release v10.0.2
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#979 patch release v10.1.2
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#987 Port dependencies bump
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#989 update common deps
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#980 Fix egl config attributes that may lead to GL fails
  DEVELOPING.md
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt
Labels: bug :beetle:

#982 enable all output report formats
  gradle/jacoco.gradle
Labels: operations, skip changelog

#996 Add changelog for v10.2.0
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#994 Add feature id to annotations; prepare showcase of callout annotations
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AnnotationWithCalloutActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/Annotation.kt
Labels: feature :green_apple:

#990 Enable drag annotation while changing the annotation to draggable in long click
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
Labels: bug :beetle:

#999 Port-Add changelog for v10.2.0 (#996)
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#920 Send turnstiles for Snapshotter usage
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
Labels: bug :beetle:

#968 [localization] lower the bar for localizing a symbol layer
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/SupportedLanguages.kt
Labels: bug :beetle:

#1001 Parse event data without json
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/ObservableExtension.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/DataSourceType.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/MapLoadErrorType.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/RenderMode.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/RequestPriority.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/RequestType.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/ResponseErrorReason.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/ResponseSourceType.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/SourceDataType.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/observable/model/StyleDataType.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/ObservableTest.kt
Labels: performance :zap:
