Repository mapbox/mapbox-maps-android, pull requests merged in 2021-08, with the labels that each got.

#534 Fixes string interpolation in font utils log message
  sdk/src/main/java/com/mapbox/maps/FontUtils.kt
Labels: skip changelog

#521 Example cleaning : update multiple geometries
  app/src/main/assets/multiple_geometry_example.geojson
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/MultipleGeometriesActivity.kt
  app/src/main/res/layout/activity_multiple_geometries.xml
Labels: skip changelog

#520 Example cleaning : Restrict map panning
  app/src/main/java/com/mapbox/maps/testapp/examples/RestrictBoundsActivity.kt
  app/src/main/res/layout/activity_restrict_bounds.xml
  app/src/main/res/menu/menu_bounds.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
Labels: skip changelog

#535 Fix ktlint on main branch
  sdk/src/main/java/com/mapbox/maps/FontUtils.kt
Labels: skip changelog

#540 Example cleaning : Data visualization
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_heatmap_layer.xml
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#536 9-patch image support
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/NinePatchImageActivity.kt
  app/src/main/res/drawable-hdpi/blue_round_nine.9.png
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/NinePatchImage.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/NinePatchUtils.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImplTest.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
Labels: feature :green_apple:

#543 Update gl-native to v10.0.0-rc.6 and common to v16.2.0
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: dependencies

#546 Fix memory leaks in SDK
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: bug :beetle:

#549 Add check for layer and source while creating annotations and init them if not initiated before
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#539 Update java API name for extension functions
  app/src/androidTest/java/com/mapbox/maps/testapp/overlay/MapOverlayPluginTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceTest.java
  app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoExt.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayExt.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarExt.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/MapboxExperimental.kt
Labels: breaking change :warning:

#551 [deps] Remove turf dependency of location component plugin.
  plugin-locationcomponent/build.gradle.kts
Labels: dependencies

#556 Fixes docstring issues for sources
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/SourceExt.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
Labels: docs :scroll:

#563 Bump gl-native to v10.0.0-rc.7, common to v17.0.0
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
Labels: dependencies

#538 Add generateId for GeoJsonSource.
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
Labels: feature :green_apple:

#545 [testapp] Add feature state example.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/featurestate/FeatureStateActivity.kt
  app/src/main/res/layout/activity_feature_state.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: skip changelog

#565 Bump gl-native to v10.0.0-rc.7.1
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#569 Fix snapshotter leak
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Labels: bug :beetle:

#568 [style-extension] Remove the expression getter/setters for source properties
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/ImageSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/ImageSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
Labels: bug :beetle:, breaking change :warning:

#571 Remove strong ref dependency in snapshotter
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Labels: bug :beetle:

#541 [deps] Bump kotlin to 1.5.21, dokka to 1.4.20, AGP to 4.2.2, jacoco to 0.8.7.
  LICENSE.md
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt
  app/src/main/res/layout/activity_annotation.xml
  app/src/main/res/layout/activity_custom_attribution.xml
  app/src/main/res/layout/activity_custom_layer.xml
  app/src/main/res/layout/activity_fill_extrusion.xml
  app/src/main/res/layout/activity_inset_map.xml
  app/src/main/res/layout/activity_map_localization.xml
  app/src/main/res/layout/activity_map_overlay.xml
  app/src/main/res/layout/activity_rts_fill_pattern_tint.xml
  app/src/main/res/layout/activity_show_hide_layers.xml
  app/src/main/res/layout/activity_view_snapshot.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Project.kt
  extension-style-app/build.gradle.kts
  gradle/jacoco.gradle
  gradle/lint.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/build.gradle.kts
Labels: feature :green_apple:, dependencies

#573 Fix maven publish configurations.
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  gradle/sdk-registry.gradle
Labels: operations, skip changelog

#575 Bump gl-native to rc.7.2, common to 17.1.0
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#579 Fix get annotation enum property crash
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
Labels: bug :beetle:

#581 Revert AGP bump
  LICENSE.md
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt
  app/src/main/res/layout/activity_annotation.xml
  app/src/main/res/layout/activity_custom_attribution.xml
  app/src/main/res/layout/activity_custom_layer.xml
  app/src/main/res/layout/activity_fill_extrusion.xml
  app/src/main/res/layout/activity_inset_map.xml
  app/src/main/res/layout/activity_map_localization.xml
  app/src/main/res/layout/activity_map_overlay.xml
  app/src/main/res/layout/activity_rts_fill_pattern_tint.xml
  app/src/main/res/layout/activity_show_hide_layers.xml
  app/src/main/res/layout/activity_view_snapshot.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Project.kt
  extension-style-app/build.gradle.kts
  gradle/jacoco.gradle
  gradle/lint.gradle
  gradle/wrapper/gradle-wrapper.properties
  sdk/build.gradle.kts
Labels: skip changelog

#584 fix uppercase bug
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
Labels: skip changelog

#601 [locationcomponent] Enable location-indicator model type for 3D location puck.
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
Labels: feature :green_apple:
