Repository mapbox/mapbox-maps-android, pull requests merged in 2021-06, with the labels that each got.

#380 Geojson async data parsing: fixes and improvements
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
Labels: bug :beetle:

#374 Add java example for DSL and add java annotations to StyleExtensionImpl
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/ExampleOverviewActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
Labels: skip changelog

#382 Add mbx-ci for release
  .circleci/config.yml
Labels: skip changelog

#384 Update changelog for beta.21
  CHANGELOG.md
Labels: skip changelog

#387 [style] rename setter for Light object from add to set
  app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
Labels: breaking change :warning:

#389 Bump the README.md to use beta.21 reference.
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#392 Fixed an typo in beta.21 changelog.
  CHANGELOG.md
Labels: skip changelog

#396 Fix typo in MapboxMapUtils jvm name.
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
Labels: skip changelog

#391 [style] rename setter for Terrain object from add to set
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
Labels: breaking change :warning:

#401 Replace old render cache API with new implementation.
  sdk/src/androidTest/java/com/mapbox/maps/RenderCacheTest.kt
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/RenderCache.kt
  sdk/src/main/java/com/mapbox/maps/RenderCacheOptionsExt.kt
Labels: breaking change :warning:

#403 Use the default dataPath from core.
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt
Labels: breaking change :warning:

#404 Include xml attribute strings from res-public to sourceSet.
  plugin-attribution/build.gradle.kts
  plugin-attribution/src/main/res-public/values/public.xml
  plugin-compass/build.gradle.kts
  plugin-compass/src/main/res-public/values/public.xml
  plugin-gestures/build.gradle.kts
  plugin-locationcomponent/build.gradle.kts
  plugin-logo/build.gradle.kts
  plugin-logo/src/main/res-public/values/public.xml
  plugin-scalebar/build.gradle.kts
  plugin-scalebar/src/main/res-public/values/public.xml
  sdk/build.gradle.kts
  sdk/src/main/res-public/values/public.xml
Labels: bug :beetle:

#410 Remove usage of ambient cache from the codebase.
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: skip changelog

#406 Add changelog for v10.0.0-rc.1 release.
  CHANGELOG.md
Labels: skip changelog

#414 Update README.md to use v10.0.0-rc.1.
  CHANGELOG.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#422 Bump gl-native to v10.0.0-rc.2, introduce addPersistentLayer/isPersistentLayer API.
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: feature :green_apple:

#423 Bump telemetry to v8.0.0, android core to v5.0.0
  buildSrc/src/main/kotlin/Project.kt
Labels: feature :green_apple:

#425 Introduce size check for render cache
  sdk/src/androidTest/java/com/mapbox/maps/RenderCacheTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: bug :beetle:

#411 Add command for generate-changelog
  Makefile
Labels: skip changelog

#426 Fix memory leak on render destroy
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRendererTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxSurfaceRendererTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxTextureViewRendererTest.kt
Labels: bug :beetle:

#368 Integrate the `addPersistentStyleLayer` to annotation plugin and location component plugin.
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/LayerExtTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: feature :green_apple:

#427 Changes the visibility of jsonObject in annotation to protected, fix ConcurrentModificationException
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationClusterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolyfillAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolylineAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/Annotation.kt
Labels: breaking change :warning:, bug :beetle:

#430 Add google service location dependency to app module.
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#435 [app] Set the maximum heap size for dex operation to 4g.
  app/build.gradle.kts
Labels: skip changelog

#432 [app] Update terrain examples to use optimised RasterDemSource url.
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain/SantaCatalinaActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain/Terrain3DShowcaseActivity.kt
Labels: skip changelog

#437 Add command to generate and upload docs locally
  Makefile
  scripts/update-android-docs.sh
Labels: skip changelog

#436 Add activity showcasing style cross fading
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/StyleCrossFadeAnimationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/StyleSwitcher.kt
  app/src/main/res/layout/activity_style_cross_fade.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
Labels: feature :green_apple:

#439 Fix camera deadlock use-case
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/HighLevelAnimatorSet.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: bug :beetle:

#379 Add Localization Api
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/localization/LocalizationActivity.kt
  app/src/main/res/drawable/ic_translate_white_24dp.xml
  app/src/main/res/layout/activity_map_localization.xml
  app/src/main/res/menu/menu_languages.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
  extension-localization/.gitignore
  extension-localization/README.md
  extension-localization/build.gradle.kts
  extension-localization/gradle.properties
  extension-localization/src/main/AndroidManifest.xml
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/StyleInterfaceExtension.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/SupportedLanguages.kt
  extension-localization/src/test/java/com/mapbox/maps/extension/localization/SupportedLanguagesTest.kt
  sdk/build.gradle.kts
  settings.gradle.kts
Labels: feature :green_apple:

#438 [build] Publish snapshot when the commit message contains publish_android_snapshot keyword.
  .circleci/config.yml
Labels: operations

#444 Coalesce to the default language if not supported
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/SupportedLanguages.kt
Labels: skip changelog

#446 Fix the wrong path in update-android-docs.sh
  scripts/update-android-docs.sh
Labels: skip changelog

#445 Changelog for v10.0.0-rc.2
  CHANGELOG.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#442 [deps] Bump gl-native to v10.0.0-rc.3, common to v14.2.0
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/ShadowMap.java
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Labels: feature :green_apple:

#457 [deps] Bump telemetry to 8.1.0
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#441 Fix annotation update missing issue.
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationWithMultiManagersTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolygoneAnnotationActivity.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#455 Perform annotation click synchronously
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationClusterActivity.kt
  app/src/main/res/menu/menu_symbol.xml
  app/src/main/res/values/strings.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapFeatureQueryDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Labels: breaking change :warning:, bug :beetle:

#449 [style] Optimise the style#getLayer and style#getSource APIs.
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
Labels: performance :zap:

#462 [build] Rename dependencies name from googleServicesLocation to googlePlayServicesLocation
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#463 Changelog for rc.3
  CHANGELOG.md
Labels: skip changelog
