Repository mapbox/mapbox-maps-android, pull requests merged in 2021-09, with the labels that each got.

#599 [gestures] use the gesture focal point for fling displacement
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesConstants.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
Labels: bug :beetle:

#602 Allow empty geojson source
  app/src/main/AndroidManifest.xml
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
Labels: bug :beetle:

#604 Bump gl-native to 10.0.0-rc.8, common to 18.0.0
  LICENSE.md
  app/src/main/java/com/mapbox/maps/testapp/examples/camera/RestrictBoundsActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/CustomLayerActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/NativeCustomLayerActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: dependencies

#598 Preserve EGL setup on renderer stop
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#606 Integrate value marshalling performance improvement
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarLocationPuck.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/RawExpressionActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/RawGeoJsonActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/RawSourceLayerActivity.kt
  app/src/main/res/values/example_descriptions.xml
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/ShadowValueConverter.java
  extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/ShadowValueConverter.java
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/common/ShadowValueConverter.java
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/ObservableExtension.kt
  sdk/src/test/java/com/mapbox/common/ShadowValueConverter.java
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt
Labels: performance :zap:

#582 Introduce drag layer/source for annotation plugin
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: performance :zap:

#597 Fix camera animators ordering on Android 6 and lower
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/OngoingAnimationActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsChangeListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: bug :beetle:

#609 Update prefetch zoom delta documentation to match actual behavior
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
Labels: docs :scroll:

#616 [style] add support for the index-of and slice expressions:
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/dsl/generated/ExpressionDsl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt
Labels: feature :green_apple:

#605 Add api check scripts
  .circleci/config.yml
  Makefile
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
  scripts/semver-check.sh
Labels: skip changelog

#621 Remove mbx-ci setup in snapshot build
  .circleci/config.yml
Labels: skip changelog

#620 Add changelog for rc.8
  CHANGELOG.md
  extension-androidauto/README.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#624 Add Android Auto CI setup.
  .circleci/config.yml
Labels: skip changelog

#629 #618: continue to listen for event while map is stopped.
  app/src/androidTest/java/com/mapbox/maps/testapp/LoadStyleCallbackTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/TestMapActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
Labels: bug :beetle:

#637 Add parametrized tests
  extension-localization/src/test/java/com/mapbox/maps/extension/localization/SupportedLanguagesTest.kt
  sdk-base/src/test/java/com/mapbox/maps/util/MathUtilsTest.kt
Labels: skip changelog, testing :100:

#639 Fix drag annotation blink issue
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#645 [docs] Fix documentation for OnMapIdleListener and CameraChangeListeners.
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapIdleListener.kt
Labels: docs :scroll:

#638 Add support for SymbolZOrder in PointAnnotationManager
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/res/menu/menu_symbol.xml
  app/src/main/res/values/strings.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
Labels: feature :green_apple:

#644 Equals and hashcode tests
  buildSrc/src/main/kotlin/Project.kt
  extension-style/build.gradle.kts
  extension-style/src/test/java/com/mapbox/maps/extension/style/EqualHashCodeTest.kt
  module-telemetry/build.gradle.kts
  module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapLoadEvent.kt
  module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/PerformanceEvent.kt
  module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/EqualHashCodeTest.kt
  sdk-base/build.gradle.kts
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorOptions.kt
  sdk-base/src/test/java/com/mapbox/maps/EqualHashCodeTest.kt
Labels: skip changelog, testing :100:

#640 Apply annotation manager properties to drag layer
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#648 Fix typo in developing.md
  DEVELOPING.md
Labels: skip changelog, docs :scroll:

#633 Fix point annotation update bitmap affect others issue.
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/res/menu/menu_symbol.xml
  app/src/main/res/values/strings.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
Labels: bug :beetle:

#651 Revert "Change the logic of handling geojson update"
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
Labels: skip changelog

#646 [deps] Bump gl-native to 10.0.0-rc.9, common to 19.0.0.
  buildSrc/src/main/kotlin/Project.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/Formatted.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
Labels: dependencies

#643 Fix getStyle returns null after adding a source
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#650 Enable annotations to set null value to nullable properties.
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#636 Add support for promoteId
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/PromoteId.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/utils/PromoteIdTest.kt
Labels: feature :green_apple:

#654 Expose optimizeForTerrain flag
  sdk/src/main/java/com/mapbox/maps/MapAttributeParser.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/res-public/values/public.xml
  sdk/src/main/res/values/attrs.xml
  sdk/src/test/java/com/mapbox/maps/MapAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
Labels: feature :green_apple:

#657 Fix memory leak in renderer destroy
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/WorkerHandlerThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: bug :beetle:

#659 Fix promoteid style test
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
Labels: bug :beetle:, skip changelog

#658 Add change log for v10.0.0-rc.9
  CHANGELOG.md
Labels: skip changelog

#653 Throw exception when gestures plugin is missing when trying to use
  buildSrc/src/main/kotlin/Project.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#663 [doc] Bump SDK version to rc.9 in READMEs.
  CHANGELOG.md
  extension-androidauto/README.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#666 Add mbx-ci for release
  .circleci/config.yml
Labels: skip changelog

#671 #669: try to fix black screen on emulator
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
Labels: bug :beetle:

#656 Add JvmOverloads for java api
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarJavaInterfaceChecker.java
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceTest.java
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarUtils.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/StyleInterfaceExtension.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/types/FormatSection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/image/NinePatchUtils.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationConfig.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationSourceOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/ClusterOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionParserConfig.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettings.kt
  sdk/src/main/java/com/mapbox/maps/MapAttributeParser.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/SnapshotOverlayOptions.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
Labels: breaking change :warning:

#668 Throw exception when camera plugin is missing
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#679 Update pull request template with jvm annotations
  .github/pull_request_template.md
Labels: skip changelog

#688 Fix map render deadlock on Android 8 on power on button
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#686 Fix failed lint tests
  mapbox-lint/src/test/java/com/mapbox/maps/lint/LifecycleMethodDetectorTest.kt
Labels: skip changelog

#689 Add CODEOWNERS.
  .github/CODEOWNERS
Labels: operations

#691 Move EGL no current context to surface creation
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: skip changelog

#672 [gestures] Refactor gestures configuration options to be aligned better across platforms.
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
  app/src/main/res/layout/activity_style_switch.xml
  app/src/main/res/layout/generated_test_gestures.xml
  app/src/main/res/menu/menu_gestures.xml
  app/src/main/res/values/strings.xml
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt
  plugin-gestures/src/main/res-public/values/public.xml
  plugin-gestures/src/main/res/values/attrs.xml
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
Labels: breaking change :warning:

#692 Fix JavaInterfaceChecker due to gesture settings change.
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
Labels: skip changelog

#690 Fix context leak in LocationProviderImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
Labels: bug :beetle:

#697 Bump gl-native to v10.0.0, common to v20.0.0
  app/src/androidTest/java/com/mapbox/maps/testapp/observable/ObservableExtensionTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/ExampleCustomLayer.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/NativeExampleCustomLayer.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/customlayer/TriangleCustomLayer.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/StyleSwitcher.kt
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
Labels: dependencies

#694 Remove cross fade example activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/StyleCrossFadeAnimationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/StyleSwitcher.kt
  app/src/main/res/layout/activity_style_cross_fade.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
Labels: skip changelog

#687 Explicitly null map reference from renderer
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: bug :beetle:
