Repository mapbox/mapbox-maps-android, pull requests merged in 2021-11, with the labels that each got.

#794 Update README versions to v10.1.0-rc.1, update snapshot version.
  extension-localization/README.md
  extension-style/README.md
  gradle.properties
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#695 add compose test app
  compose/.gitignore
  compose/app/.gitignore
  compose/app/build.gradle
  compose/app/proguard-rules.pro
  compose/app/src/main/AndroidManifest.xml
  compose/app/src/main/java/com/mapbox/maps/compose/MainActivity.kt
  compose/app/src/main/java/com/mapbox/maps/compose/ui/theme/Color.kt
  compose/app/src/main/java/com/mapbox/maps/compose/ui/theme/Shape.kt
  compose/app/src/main/java/com/mapbox/maps/compose/ui/theme/Theme.kt
  compose/app/src/main/java/com/mapbox/maps/compose/ui/theme/Type.kt
  compose/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  compose/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  compose/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  compose/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  compose/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  compose/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  compose/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  compose/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  compose/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  compose/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  compose/app/src/main/res/values-night/themes.xml
  compose/app/src/main/res/values/colors.xml
  compose/app/src/main/res/values/ic_launcher_background.xml
  compose/app/src/main/res/values/strings.xml
  compose/app/src/main/res/values/themes.xml
  compose/build.gradle
  compose/gradle.properties
  compose/gradle/wrapper/gradle-wrapper.jar
  compose/gradle/wrapper/gradle-wrapper.properties
  compose/gradlew
  compose/gradlew.bat
  compose/settings.gradle
Labels: skip changelog

#799 Enable create pr in CI automatically
  .circleci/config.yml
  Makefile
  scripts/update-android-docs.sh
Labels: skip changelog, workflow :nail_care:

#808 remove useless CI job build-sdk-from-source
  .circleci/config.yml
Labels: skip changelog, workflow :nail_care:

#807 Add pipline to trigger generating docs in internal repo
  .circleci/config.yml
  scripts/generate-docs-start-pipeline.py
Labels: skip changelog, workflow :nail_care:

#804 Automatically generate checksum for all project modules
  .circleci/config.yml
  .gitignore
  scripts/checksum.sh
Labels: skip changelog

#810 Bump gl-native to 10.1.0, common to 20.1.0
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#811 Update change log for 10.1.0
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#819 Update key name for version number
  scripts/update-android-docs.sh
Labels: skip changelog

#766 Enable AnnotationManager independent on MapView
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationClusterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolygoneAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolylineAnnotationActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/Annotation.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
Labels: feature :green_apple:

#816 refactor build stages. save apk to workspace before instrumentation tests
  .circleci/config.yml
Labels: operations, skip changelog

#827 Apply ratio to the width of scalebar
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
Labels: bug :beetle:

#823 Update update-android-docs.sh to upload the correct docs
  scripts/update-android-docs.sh
Labels: skip changelog

#594 View Annotations feature
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
  app/src/main/res/drawable/bg.xml
  app/src/main/res/layout/activity_view_annotation_showcase.xml
  app/src/main/res/layout/item_callout_view.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  buildSrc/src/main/kotlin/Project.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ViewPlugin.kt
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationOptionsKtx.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewPosition.kt
Labels: feature :green_apple:

#839 Fix scale bar texts missing on devices with Android 6 issue
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
Labels: bug :beetle:

#842 Annotation manager cleanup
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationWithMultiManagersTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnimatePointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
Labels: skip changelog

#841 fix number format test
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
Labels: testing :100:

#848 add template for before-after block in PR template for better visualization
  .github/pull_request_template.md
Labels: skip changelog, docs :scroll:

#849 merge flavors build for app on CI
  .circleci/config.yml
Labels: operations, skip changelog

#780 [lifecycle-plugin] Use ComponentCallbacks2 instead ComponentCallbacks and hook into onTrimMemory.
  plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
  plugin-lifecycle/src/test/java/com/mapbox/common/ShadowLogger.java
  plugin-lifecycle/src/test/java/com/mapbox/maps/extension/lifecycle/MapboxLifecyclePluginImplTest.kt
Labels: feature :green_apple:

#852 Bump gl-native to v10.2.0-beta.2 and common to v21.0.0-rc.1
  app/src/main/java/com/mapbox/maps/testapp/examples/HeatmapLayerActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapProjection.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapFeatureQueryDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTypedArrayTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapDelegateProviderTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapPluginRegistryTest.kt
Labels: dependencies

#773 Implement cluster API on top of queryFeatureExtensions
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#826 Add example that uses tilejson through the tileset class.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#856 Fix Scale bar texts overlap and clipped issue
  plugin-scalebar/build.gradle.kts
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt
Labels: bug :beetle:

#859 add merge-main flag for circle ci pipeline
  .circleci/config.yml
  scripts/ci-circleci-start-pipeline.py
Labels: operations, skip changelog

#846 Set last puck position on every settings change.
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/util/MockKExtensions.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
Labels: bug :beetle:

#858 Add scale listener events for double tap and double finger tap gesture
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureActivityTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
Labels: bug :beetle:

#834 Feature: view annotations support
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
  app/src/main/res/drawable/ic_callout_item_background.xml
  app/src/main/res/layout/activity_view_annotation_showcase.xml
  app/src/main/res/layout/item_callout_view.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Project.kt
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationOptionsKtx.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerAddTest.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: feature :green_apple:

#864 Add change log for 10.2.0-beta.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#866 Trigger release job for release tag.
  .circleci/config.yml
Labels: skip changelog

#865 update developing.md file
  DEVELOPING.md
Labels: skip changelog, docs :scroll:

#873 [examples] Basic view annotation example activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#869 [gestures] Refactor fling gestures test to be parameterised tests.
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: skip changelog, testing :100:

#879 [style] Promote persistent style layer APIs to be production-ready.
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: feature :green_apple:

#884 Fix npm vulnerabilities.
  package-lock.json
Labels: operations, skip changelog

#882 Add step to PR template
  .github/pull_request_template.md
Labels: skip changelog

#878 Cancellable queryRenderFeatures
  app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/featurestate/FeatureStateActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/IconSizeChangeOnClickActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapFeatureQueryDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: skip changelog

#890 Revert Dokka to 1.4.10.2; only generate docs for stable releases.
  .circleci/config.yml
  buildSrc/src/main/kotlin/Project.kt
  scripts/update-android-docs.sh
Labels: skip changelog

#896 Prevent multiple usage of associatedFeatureId in view annotations
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: bug :beetle:

#897 Port: prevent multiple usage of associatedFeatureId in view annotations
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: bug :beetle:

#875 [Gesture] Update default shove gesture angle
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: bug :beetle:

#894 View annotations: add instrument tests
  sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/androidTest/res/layout/view_annotation.xml
Labels: skip changelog, testing :100:

#903 Port view annotations: add instrument tests
  sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/androidTest/res/layout/view_annotation.xml
Labels: skip changelog, testing :100:

#904 Allow load empty style uri
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#909 revert jcenter to fix ci job
  build.gradle.kts
  settings.gradle.kts
Labels: skip changelog, dependencies

#906 Add Style#removeTerrain and Style#removeLight methods
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/TerrainExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt
Labels: feature :green_apple:

#911 Prepare patch release v10.0.1
  CHANGELOG.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#913 Add changelog for v10.0.1
  CHANGELOG.md
Labels: skip changelog

#912 Reorder sections in PR template
  .github/pull_request_template.md
Labels: skip changelog

#900 [Doc] Fix geojson doc for listener events
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnSourceDataLoadedListener.kt
Labels: skip changelog, docs :scroll:

#902 Update api check script
  .circleci/config.yml
  scripts/java-api-check-all.sh
  scripts/java-api-check.json
  scripts/java-api-check.sh
  scripts/semver-check.sh
Labels: skip changelog

#893 [Testing] Fix Geojson flaky test
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/ImageSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
Labels: skip changelog, testing :100:

#885 Simultaneous zoom and rotate gesture
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  app/src/main/res/layout/generated_test_gestures.xml
  plugin-gestures/build.gradle.kts
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt
  plugin-gestures/src/main/res-public/values/public.xml
  plugin-gestures/src/main/res/values/attrs.xml
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
Labels: feature :green_apple:

#925 Bump gl-native to v10.2.0-rc.1
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#926 Fix concurrent modification exception in example
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/SnakingDirectionsRouteActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
Labels: skip changelog

#924 Update section about release management
  DEVELOPING.md
Labels: skip changelog
