Repository mapbox/mapbox-maps-android, pull requests merged in 2021-03, with the labels that each got.

#137 [deps] Bump gl-native to v10.0.0-beta.16, common to beta.12.
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/main/java/com/mapbox/maps/MapAttributeParser.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/res-public/values/public.xml
  sdk/src/main/res/values/attrs.xml
  sdk/src/test/java/com/mapbox/maps/MapAttributeParserTest.kt
Labels: breaking change :warning:

#139 [map] Remove unused configuration enum properties.
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
Labels: skip changelog

#155 Update sdk version to beta.15 in readmes
  extension-observable/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-location/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#141 Fix typo in MapOverlay README
  plugin-overlay/README.md
Labels: skip changelog

#161 [Annotation plugin] Implement MapStyleObserverPlugin to listen style load event to reload layer and source
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
Labels: bug :beetle:

#166 Refactor Event API into new Observers.
  app/build.gradle.kts
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  extension-observable/.gitignore
  extension-observable/README.md
  extension-observable/build.gradle.kts
  extension-observable/gradle.properties
  extension-observable/src/main/AndroidManifest.xml
  extension-observable/src/main/java/com/mapbox/maps/extension/observable/ObservableExtension.kt
  extension-style-app/build.gradle.kts
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationLayerWrapper.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationPluginImpl.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/ModelLocationSourceWrapper.kt
  plugin-location/src/test/java/com/mapbox/maps/plugin/location/IndicatorLocationLayerWrapperTest.kt
  plugin-location/src/test/java/com/mapbox/maps/plugin/location/ModelLocationLayerWrapperTest.kt
  plugin-location/src/test/java/com/mapbox/maps/plugin/location/ModelLocationSourceWrapperTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapStyleObserverPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapListenerDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnDidFinishRenderingFrameListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnDidFinishRenderingMapListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapChangedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapIdleListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapLoadErrorListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapLoadingFinishedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnRenderFrameFinishedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnRenderFrameStartedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnSourceAddedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnSourceRemovedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnStyleFullyLoadedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnStyleImageChangeListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnStyleImageMissingListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnStyleImageUnusedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnStyleLoadingFinishedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/eventdata/MapLoadError.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/eventdata/RenderMode.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapObserver.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/ObservableExtension.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/map/IDStringEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/map/MapLoadingErrorEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/map/RenderFrameFinishedEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Error.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Request.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/ResourceEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Response.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/test/java/com/mapbox/common/ShadowValueConverter.java
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapPluginRegistryTest.kt
  settings.gradle.kts
Labels: breaking change :warning:

#122 [Annotation plugin] Add symbol cluster support
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnnotationUtils.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolClusterActivity.kt
  app/src/main/res/layout/activity_annotation.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationSourceOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/ClusterOptions.kt
Labels: feature :green_apple:

#171 [gestures] Fix crash if zooming for SDK <= 23
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/Evaluators.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
Labels: bug :beetle:

#173 [Annotation plugin] Set default values for annotation option properties to null.
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Circle.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Fill.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Line.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineOptions.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
Labels: performance :zap:

#190 Fix main after gl bump
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnnotationUtils.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolClusterActivity.kt
Labels: skip changelog

#187 [doc] Change http link to markdown style in doc
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/types/FormatSection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/Formatted.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/Utils.java
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationSourceOptions.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: docs :scroll:

#193 Fix onStop and onStart for NativeObserver, fix removing map error load listener
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: skip changelog

#192 [rendering] Differentiate render tasks and non-render tasks
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: feature :green_apple:

#185 [locationcomponent] Fix jitter animations if interrupting animations
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt
Labels: bug :beetle:

#198 [animation] Fix zero duration animators, fix medium-level animators
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
Labels: bug :beetle:

#201 [gestures] Introduce platform-driven drag API to move a map
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapTransformDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: feature :green_apple:

#202 [animations] Fix interpolation for flyTo
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
Labels: bug :beetle:

#200 [sdk] Remove MapObserver from MapSurface's constructor.
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/wallpaper/MapWallpaper.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
Labels: breaking change :warning:

#209 [doc] Remove MapObserver reference from the codebase.
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: docs :scroll:, skip changelog

#210 Remove usage of MapSnapshotterObserver and use Observerable API instead.
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Labels: skip changelog

#214 Fix legacy location plugin stackoverflow error
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraAnimatorCoordinator.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraController.kt
  plugin-location/src/test/java/com/mapbox/maps/plugin/location/LocationCameraControllerTest.kt
Labels: skip changelog

#211 [changelog] Update change log for v10.0.0-beta.16
  CHANGELOG.md
Labels: skip changelog

#215 [doc] Update plugin version to v10.0.0-beta.16 in the README.
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-location/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog
