Repository mapbox/mapbox-maps-android, pull requests merged in 2021-07, with the labels that each got.

#464 [style] restore recent changes to generated style code
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
Labels: skip changelog

#468 Update md files to use v10.0.0-rc.3
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#461 [Localization] Add new param to allow users localize selected layers.
  app/src/main/java/com/mapbox/maps/testapp/examples/localization/LocalizationActivity.kt
  app/src/main/res/menu/menu_languages.xml
  app/src/main/res/values/strings.xml
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/StyleInterfaceExtension.kt
Labels: feature :green_apple:

#454 Add RuntimeStylingJavaActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/SourceExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/TerrainExt.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: skip changelog

#474 Add API to control logs for animators
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
Labels: feature :green_apple:

#458 Introduce option to use continuous rendering for scale bar
  app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserTest.kt
  app/src/main/res/layout/generated_test_scalebar.xml
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParser.kt
  plugin-scalebar/src/main/res-public/values/public.xml
  plugin-scalebar/src/main/res/values/attrs.xml
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParserTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettingsInterface.kt
Labels: feature :green_apple:

#473 Add shortest bearing path option for animators
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraBearingAnimator.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsChangeListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraTransformTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/utils/MathUtils.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/util/MathUtils.kt
  sdk-base/src/test/java/com/mapbox/maps/util/MathUtilsTest.kt
Labels: breaking change :warning:, feature :green_apple:

#472 Add example AnimateAnnotationActivity.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnimatePointAnnotationActivity.kt
  app/src/main/res/drawable-xxxhdpi/ic_car_top.png
  app/src/main/res/drawable-xxxhdpi/ic_taxi_top.png
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  scripts/ci-circleci-start-pipeline.py
Labels: skip changelog

#478 Fix flyTo crash when using single-pixel paddings
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt
Labels: bug :beetle:

#477 Update title, package and category for 3D examples
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/FillExtrusionActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/Terrain3DShowcaseActivity.kt
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#484 [CameraAnimationsPluginImpl] Fix camera animations on Android 6
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraOptionsUtils.kt
Labels: bug :beetle:

#487 Update gl-native to v10.0.0-rc.5 and common to v16.0.0
  app/proguard-rules.pro
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#493 Add modelTranslation support for LocationPuck3D
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
Labels: feature :green_apple:

#491 [sdk-base] add default parameters to coordinate conversion functions
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#500 Add changelog for rc.4
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#492 Update offline tests to reflect to latest upstream changes
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: testing :100:

#495 [camera] improve camera API for java
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceTest.java
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
Labels: breaking change :warning:

#496 Add showLogo and showAttributes config for snapshotter
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
  sdk/src/main/java/com/mapbox/maps/SnapshotOverlayOptions.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
Labels: feature :green_apple:

#504 Update titles and category for lines and polygon, align with gl-js implementation.
  app/src/main/AndroidManifest.xml
  app/src/main/assets/from_crema_to_council_crest.geojson
  app/src/main/assets/maine_polygon.geojson
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/DrawGeoJsonLineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/DrawPolygonActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/LineGradientActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/MovingIconWithTrailingLineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/SnakingDirectionsRouteActivity.kt
  app/src/main/res/layout/activity_dds_draw_geojson_line.xml
  app/src/main/res/layout/activity_dds_draw_polygon.xml
  app/src/main/res/layout/activity_rts_fill_pattern_tint.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#497 [build] update code to be Android 12 target SDK compatible
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/AnimatedImageSourceActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceActivity.kt
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionViewImpl.kt
  plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewImplTest.kt
  plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewPluginImplTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
Labels: breaking change :warning:

#505 Example cleaning - Markers and callouts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AddMarkersSymbolActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AddOneMarkerSymbolActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AnimatedMarkerActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/IconSizeChangeOnClickActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/MultipleGeometriesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationClusterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolygoneAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolylineAnnotationActivity.kt
  app/src/main/res/layout/activity_add_marker_symbol.xml
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#508 Fix issues with MapView#snapshot methods
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/gl/PixelReader.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: bug :beetle:

#507 Remove generate-docs step in release
  .circleci/config.yml
Labels: skip changelog

#509 Re-enable snapshotter sanity test
  sdk/src/androidTest/java/com/mapbox/maps/MapSnapshotterTest.kt
Labels: skip changelog

#510 [ci] Add commit hash to the snapshots' name built on main branch.
  .circleci/config.yml
Labels: operations

#485 Add lifecycle plugin
  app/src/main/java/com/mapbox/maps/testapp/examples/SimpleMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnimatePointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/fragment/MapFragment.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationClusterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolygoneAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PolylineAnnotationActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  plugin-lifecycle/.gitignore
  plugin-lifecycle/README.md
  plugin-lifecycle/build.gradle.kts
  plugin-lifecycle/gradle.properties
  plugin-lifecycle/src/main/AndroidManifest.xml
  plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
  plugin-lifecycle/src/test/java/com/mapbox/maps/extension/lifecycle/MapboxLifecyclePluginImplTest.kt
  sdk-base/src/main/java/com/mapbox/maps/MapboxLifecycleObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/Plugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePlugin.kt
  sdk/build.gradle.kts
  sdk/src/androidTest/java/com/mapbox/maps/LifecycleTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
  settings.gradle.kts
Labels: feature :green_apple:

#512 [ci] Increase robo test and build sdk release CI bot's resources to fix flaky tests due to OOM.
  .circleci/config.yml
Labels: operations, skip changelog

#488 [android-auto] Add a minimum Android Auto test app and Android Auto extension.
  .gitignore
  Makefile
  android-auto-app/build.gradle.kts
  android-auto-app/src/main/AndroidManifest.xml
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarLocationPuck.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapSession.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/RequestPermissionScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/service/MapboxCarAppService.kt
  android-auto-app/src/main/res/drawable/ic_pan_24.xml
  android-auto-app/src/main/res/drawable/ic_zoom_in_24.xml
  android-auto-app/src/main/res/drawable/ic_zoom_out_24.xml
  android-auto-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android-auto-app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android-auto-app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android-auto-app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android-auto-app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android-auto-app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android-auto-app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  android-auto-app/src/main/res/values/dimens.xml
  android-auto-app/src/main/res/values/ic_launcher_background.xml
  android-auto-app/src/main/res/values/strings.xml
  android-auto-app/src/main/res/values/themes.xml
  android-auto-app/src/main/res/xml/automotive_app_desc.xml
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/.gitignore
  extension-androidauto/README.md
  extension-androidauto/build.gradle.kts
  extension-androidauto/gradle.properties
  extension-androidauto/src/main/AndroidManifest.xml
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarUtils.kt
  settings.gradle.kts
Labels: feature :green_apple:

#516 Add lint check for lifecycle methods
  buildSrc/src/main/kotlin/Project.kt
  mapbox-lint/.gitignore
  mapbox-lint/build.gradle
  mapbox-lint/src/main/java/com/mapbox/maps/lint/LifecycleIssueRegistry.kt
  mapbox-lint/src/main/java/com/mapbox/maps/lint/LifecycleMethodDetector.kt
  mapbox-lint/src/main/resources/META-INF/services/com.android.tools.lint.client.api.IssueRegistry
  mapbox-lint/src/test/java/com/mapbox/maps/lint/LifecycleMethodDetectorTest.kt
  plugin-lifecycle/build.gradle.kts
  settings.gradle.kts
Labels: feature :green_apple:

#523 [doc] Add guide to snapshot releases in DEVELOPING.md
  DEVELOPING.md
Labels: docs :scroll:, skip changelog

#519 Remove plugin reflection
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/Plugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapPluginProviderDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/LifecycleTest.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Utils.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapPluginRegistryTest.kt
Labels: breaking change :warning:, feature :green_apple:

#526 Fix memory leak in lifecycle plugin
  plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
Labels: skip changelog

#513 [ci] move from mapbox-maps-stylegen to mapbox-maps-android-internal
  .circleci/config.yml
  scripts/ci-circleci-start-pipeline.py
Labels: skip changelog
