Repository mapbox/mapbox-maps-android, pull requests merged in 2021-10, with the labels that each got.

#667 3D globe
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/GlobeActivity.kt
  app/src/main/res/layout/activity_globe_view.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapProjection.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/GlobeIntegrationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapProjectionUtils.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#699 Remove sync parsing geojson option
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  app/src/main/java/com/mapbox/maps/testapp/examples/LargeGeojsonPerformanceActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/OnGeoJsonParsed.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/SourceExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
  sdk/build.gradle.kts
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: breaking change :warning:

#702 WaitForIdle before perform flaky instrumentation test
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/surface/SurfaceViewOrientationChangeTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/texture/TextureViewOrientationChangeTest.kt
Labels: skip changelog, testing :100:

#708 Fix wrong attribute reference when token is missing
  sdk/src/main/java/com/mapbox/maps/MapboxConfigurationException.kt
Labels: bug :beetle:

#707 Update deprecated robo device
  .circleci/config.yml
Labels: skip changelog

#700 Stop publishing Android Auto extension together with the SDK.
  extension-androidauto/build.gradle.kts
Labels: skip changelog

#710 Update 3D puck model for examples
  app/src/main/assets/race_car_model.gltf
  app/src/main/assets/sportcar.glb
  app/src/main/java/com/mapbox/maps/testapp/examples/GlobeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
Labels: skip changelog

#673 fix getLayerAs return optional Layer type.
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
  extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
Labels: breaking change :warning:

#677 Fix scaleBar position property not working issue.
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
Labels: bug :beetle:

#712 [observable-extension] Update map events data models.
  app/src/androidTest/java/com/mapbox/maps/testapp/LoadStyleCallbackTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/observable/ObservableExtensionTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapLoadErrorListener.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/model/MapLoadingErrorEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Error.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Request.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/ResourceEventData.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Response.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/DataSourceType.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/RequestPriority.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/RequestType.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/ResponseErrorType.kt
  sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/ResponseSourceType.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt
Labels: breaking change :warning:

#664 Add JvmOverloads for Compass plugin
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/main/res/values/dimens.xml
Labels: skip changelog

#711 [docs] append upstream documentation to project
  .gitignore
  Makefile
  scripts/update-android-docs.sh
  sdk/build.gradle.kts
Labels: docs :scroll:

#680 Call plugin onStart after start loading style
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Labels: bug :beetle:

#720 v10.0.0 changelog
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog
