Repository mapbox/mapbox-maps-android, pull requests merged in 2021-04, with the labels that each got.

#229 [changelog] Fix the change log for beta.16.
  CHANGELOG.md
Labels: skip changelog

#237 [javadoc] Update docs about right time to call some transformation functions
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: docs :scroll:

#208 [docs] Add script to auto generate docs and create pull request while releasing
  .circleci/config.yml
  .gitignore
  Makefile
  scripts/update-android-docs.sh
Labels: docs :scroll:

#240 Fix runtime crash if logo / attribution not enabled
  sdk/src/main/java/com/mapbox/maps/MapController.kt
Labels: bug :beetle:

#247 [deps] Bump gl-native to v10.0.0-beta.19, common to v11.0.0
  app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/IconSizeChangeOnClickActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: breaking change :warning:

#249 Update changelog for v10.0.0-beta.17
  CHANGELOG.md
Labels: skip changelog

#252 Keep CompassPlugin enabled/disabled state after other properties update
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
Labels: bug :beetle:

#254 Force checkout branch while preparing branch with documentation
  scripts/update-android-docs.sh
Labels: skip changelog

#255 [example] Fix IndexOutOfBoundsException in test app
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/ExampleOverviewActivity.kt
Labels: skip changelog

#258 Bump sdk version to v10.0.0-beta.17 in readme
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-location/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#263 Disable codecov
  .circleci/config.yml
  DEVELOPING.md
Labels: skip changelog

#261 [deps] Bump gl-native to v10.0.0-beta.20, common to v11.0.1
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
Labels: breaking change :warning:

#268 Remove the prefix for tag name in update-android-docs.sh
  scripts/update-android-docs.sh
Labels: skip changelog

#269 Add feature sdk initialisation
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SimpleMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/fragment/MapFragment.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/main/java/com/mapbox/maps/CredentialsManager.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMapOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapboxOptions.kt
  sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/main/res/values/attrs.xml
  sdk/src/test/java/com/mapbox/maps/CredentialsManagerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapPluginRegistryTest.kt
Labels: skip changelog

#262 [animation] High-level animations return cancelable interface
  app/src/main/java/com/mapbox/maps/testapp/examples/CameraPredefinedAnimatorsActivity.kt
  app/src/main/res/layout/activity_camera_predefined_animators.xml
  app/src/main/res/values/strings.xml
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/HighLevelAnimatorSet.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-location/src/test/java/com/mapbox/maps/plugin/location/LocationCameraControllerTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/animation/Cancelable.kt
Labels: feature :green_apple:

#275 Fix the MapOptions and ResourceOptions default values.
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
Labels: skip changelog

#272 [API] Rename MapView plugin extension functions
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/attribution/generated/AttributionAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/attribution/generated/AttributionAttributeParserTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/compass/generated/CompassAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/compass/generated/CompassAttributeParserTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureActivityTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/location/LocationComponentTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/logo/generated/LogoAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/logo/generated/LogoAttributeParserTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/overlay/MapOverlayPluginTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/BasicLocationPulsingCircleActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/CameraPredefinedAnimatorsActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/CustomAttributionActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationModesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LowLevelCameraAnimatorActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/TextureViewAnimateActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationClusterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolyfillAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolylineAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerShowcaseActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain/SantaCatalinaActivity.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt
  plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  sdk/src/androidTest/java/com/mapbox/maps/BaseAnimationMapTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: breaking change :warning:, feature :green_apple:

#273 [logo] Fix disabling logo in xml
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionViewImpl.kt
  plugin-attribution/src/test/java/com/mapbox/common/ShadowLogger.java
  plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewImplTest.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewImpl.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt
  sdk-base/src/main/res/values/strings.xml
  sdk/src/main/java/com/mapbox/maps/MapController.kt
Labels: bug :beetle:

#279 [gestures] Properly reset anchor after some gestures
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
Labels: bug :beetle:

#280 [gestures] Remove animator cancel listeners logic
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
Labels: bug :beetle:

#278 Add changelog for beta.18
  CHANGELOG.md
Labels: skip changelog

#286 Bump sdk version to beta.18 in README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#292 Request layout when updating ornaments margins
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/OrnamentMarginActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
  plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewPluginImplTest.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewImpl.kt
  plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
  plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionView.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/compass/CompassView.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/logo/LogoView.kt
Labels: bug :beetle:

#295 [location] Remove runtime plugin dependency for legacy location plugin
  sdk-base/src/main/java/com/mapbox/maps/plugin/Plugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/location/LocationPlugin.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
Labels: bug :beetle:

#296 [sdk] remove temporary CustomMapInterface
  sdk/src/main/java/com/mapbox/maps/CustomMapInterface.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: breaking change :warning:

#290 [offline] Instrument tests for offline
  sdk/build.gradle.kts
  sdk/src/androidTest/java/com/mapbox/maps/LegacyOfflineManagerTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/TestActivity.kt
Labels: testing :100:

#287 Add styleUri property in MapInitOptions
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/MapboxStudioStyleActivity.kt
  app/src/main/res/layout/activity_style_mapbox_studio.xml
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
  sdk/src/main/res-public/values/public.xml
  sdk/src/main/res/values/attrs.xml
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
Labels: feature :green_apple:

#298 Fix test due to missed rebase
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: skip changelog

#293 Align MapCameraManagerDelegate with MapCameraManagerInterface
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/OrnamentMarginActivity.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt
  plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt
  plugin-overlay/src/test/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginTest.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/Annotation.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapDelegateProvider.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapTransformDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapCameraDelegateImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapDelegateProviderImpl.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
  sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapCameraDelegateImplTest.kt
  sdk/src/test/java/com/mapbox/maps/plugin/MapDelegateProviderTest.kt
Labels: breaking change :warning:

#299 Remove the exclude kotlin_module rule from package options.
  app/build.gradle.kts
  sdk/build.gradle.kts
Labels: bug :beetle:

#231 [plugin] refactor plugin setup
  app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
Labels: performance :zap:

#300 [sdk] rework style loading to avoid invoking previously set listeners
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: breaking change :warning:, bug :beetle:
