Repository mapbox/mapbox-maps-android, pull requests merged in 2022-01, with the labels that each got.

#1014 MapboxRenderer: unsubscribe from RENDER_FRAME_FINISHED after the first event
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
Labels: bug :beetle:

#1021 Support wrap content dimensions for view annotations
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AnnotationWithCalloutActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
  app/src/main/res/layout/item_callout_view.xml
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/androidTest/res/layout/view_annotation_wrap_content.xml
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
Labels: feature :green_apple:

#1035 Bump gl-native to v10.3.0-beta.1, common to v21.1.0-beta.1
  LICENSE.md
  buildSrc/src/main/kotlin/Project.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapProjection.kt
Labels: dependencies

#1037 Fix leak in view tree observer for view annotations
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: bug :beetle:

#1045 Let api check all the packages
  scripts/java-api-check.json
  scripts/java-api-check.sh
Labels: skip changelog

#1033 [viewport] Add viewport plugin.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt
  app/src/main/java/com/mapbox/maps/testapp/utils/SimulateRouteLocationProvider.kt
  app/src/main/res/layout/activity_viewport_animation.xml
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  app/src/main/res/values/strings.xml
  plugin-viewport/README.md
  plugin-viewport/build.gradle.kts
  plugin-viewport/gradle.properties
  plugin-viewport/src/main/AndroidManifest.xml
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportExt.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactory.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/TransitionUtils.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportTestConstants.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransitionImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/TransitionUtilsTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/Plugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/CompletionListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportConstants.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatus.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatusObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/DefaultViewportTransitionOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowingViewportStateBearing.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowingViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowingViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportStateDataObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/ViewportTransition.kt
  sdk-base/src/test/java/com/mapbox/maps/EqualsHashCodeTest.kt
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
  settings.gradle.kts
Labels: feature :green_apple:

#1059 Only update release version in constants of android-docs repo for stable release
  scripts/update-android-docs.sh
Labels: skip changelog

#1060 Polish codes for LocationComponentPlugin.createDefault2DPuck
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
Labels: skip changelog

#1064 [viewport] Fix an issue that causes transition not fired when bearing is set to constant.
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt
Labels: bug :beetle:

#1061 Update api-check script to skip new module and fail the job when find major change
  .circleci/config.yml
  Makefile
  scripts/java-api-check-all.sh
  scripts/java-api-check.json
  scripts/java-api-check.sh
Labels: skip changelog

#1065 Port viewport fix #1064
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt
Labels: bug :beetle:

#1066 Add job to check changelog
  .circleci/config.yml
  Makefile
  scripts/check-changelog.sh
Labels: skip changelog

#1070 [viewport] Fix default viewport transition's anchor point.
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt
Labels: bug :beetle:, skip changelog

#1067 fix 3d puck scaling issue
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: bug :beetle:

#1074 [viewport] Refine tests.
  app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransitionImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt
Labels: skip changelog, testing :100:

#1075 port 3d puck scaling fix (#1067)
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: bug :beetle:

#1079 [viewport] Align public API surface with iOS.
  plugin-viewport/README.md
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/CompletionListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportConstants.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatus.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatusObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/DefaultViewportTransitionOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateBearing.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportStatusChangeReason.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportStateDataObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/ViewportTransition.kt
Labels: skip changelog, breaking change :warning:

#1083 [deps] Port gl-native and common version bump.
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1084 Rebase v10.3 changelog to main
  CHANGELOG.md
Labels: skip changelog

#1077 Fix map not rendering on emulators when MSAA is enabled
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt
Labels: bug :beetle:

#1085 Add changelog for v10.3.0-rc.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#1091 Port 10.3.0-rc.1 changelog
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
Labels: skip changelog

#1100 Fix issue with map rendering when limiting max FPS
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#1094 Cancel offline jobs in onDestroy
  app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
Labels: skip changelog

#1090 Check api based on the last stable release
  scripts/java-api-check.sh
Labels: skip changelog

#1101 PR #1100 port to release branch
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#1103 Update minor version in gradle.properties
  gradle.properties
Labels: skip changelog
