Repository mapbox/mapbox-maps-android, pull requests merged in 2022-11, with the labels that each got.

#1751 [viewannotation] Introduce get annotations list api MAPSAND-463
  CHANGELOG.md
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: feature :green_apple:

#1753 [viewannotation] Introduce show annotations api [MAPSAND-464]
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt
  app/src/main/res/layout/activity_view_annotation_showcase.xml
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: feature :green_apple:

#1790 fix touch event for annotations
  sdk/src/main/java/com/mapbox/maps/MapView.kt
Labels: skip changelog

#1794 expose RenderWorldCopies property MAPSAND-588
  CHANGELOG.md
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#1806 Add sky layer deprecation docs
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
Labels: skip changelog

#1807 Fix Java example to show image source with raster layer
  app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
Labels: skip changelog

#1809 Port: Add sky layer deprecation docs
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
Labels: skip changelog

#1808 bump gl native v10.9.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1767 [Android Auto] Remove experimental annotation
  android-auto-app/build.gradle.kts
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapShowcase.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  extension-androidauto/CHANGELOG.md
  extension-androidauto/api/metalava.txt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandler.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.java
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.java
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSurface.kt
Labels: android auto

#1801 Set events as queued by default
  module-telemetry/build.gradle.kts
  module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapLoadEvent.kt
  module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapTelemetryImpl.kt
  module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapEventFactoryTest.kt
  module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapTelemetryTest.kt
  sdk-base/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/shadows/ShadowEventsService.kt
Labels: skip changelog

#1819 [deps] bump license plugin to v0.9.0
  LICENSE.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1820 Flush pending events for telemetry service on map controller stop.
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/shadows/ShadowTelemetryService.kt
Labels: skip changelog

#1818 port changelog v10.9.1
  CHANGELOG.md
Labels: skip changelog

#1816 Add changelog extension-androidauto-v0.4.0
  extension-androidauto/CHANGELOG.md
Labels: skip changelog, android auto

#1823 update num-flaky-test-attempts for firebase device lab
  .circleci/config.yml
Labels: skip changelog

#1825 [mapbox-lint] Add vendor configuration to LifecycleIssueRegistry.
  buildSrc/src/main/kotlin/Project.kt
  mapbox-lint/src/main/java/com/mapbox/maps/lint/LifecycleIssueRegistry.kt
Labels: skip changelog

#1831 Fix a crash after removing the view annotation if view has an attached animation or transition
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: bug :beetle:

#1835 PR #1831 port to release branch
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: bug :beetle:

#1828 [Android Auto] Bump car library to 1.2.0
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/CHANGELOG.md
Labels: android auto

#1841 add remove atmosphere api MAPSAND-601
  CHANGELOG.md
  extension-style/api/extension-style.api
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
Labels: feature :green_apple:

#1846 Update GesturesActivity example to match documentation
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
Labels: skip changelog

#1860 10.10.0-rc.1 Common SDK version typo fix
  CHANGELOG.md
Labels: skip changelog
