Repository mapbox/mapbox-maps-android, pull requests merged in 2022-04, with the labels that each got.

#1246 Enable publish Android Auto separately from the main sdk.
  .circleci/config.yml
  DEVELOPING.md
  Makefile
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/build.gradle.kts
  extension-androidauto/gradle.properties
  gradle/artifact-settings.gradle
  gradle/sdk-registry.gradle
Labels: skip changelog

#1262 [viewport] Fix camera jump when default transition is canceled.
  CHANGELOG.md
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
  plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt
Labels: bug :beetle:

#1264 Fix globe flickering when calling getter
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/ProjectionExt.kt
Labels: skip changelog

#1271 Fix latitude being NaN during flyTo
  CHANGELOG.md
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: bug :beetle:

#1272 V10.5 port: Fix latitude being NaN during flyTo
  CHANGELOG.md
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
Labels: bug :beetle:

#1267 [android-auto] Improve dependency management and documentation.
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapWidgets.kt
  extension-androidauto/README.md
  extension-androidauto/build.gradle.kts
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/CompassWidget.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/LogoWidget.kt
Labels: skip changelog, android-auto

#1257 [Android Auto] Add changelog for extension-androidauto
  extension-androidauto/CHANGELOG.md
Labels: skip changelog

#1226 Limit to the bounds of MapView.
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#1275 [ci] revert unforseen changes to CI scripts
  .circleci/config.yml
  scripts/mobile-metrics-start-pipeline.py
Labels: skip changelog

#1280 [gestures] Enable two finger pan gesture.
  CHANGELOG.md
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: bug :beetle:

#1282 [deps] Bump gl-native v10.5.0-rc.1, common v21.3.0-rc.2
  CHANGELOG.md
  LICENSE.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1304 Fix some render tasks being skipped
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
Labels: bug :beetle:

#1305 Fix some render tasks being skipped
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
Labels: bug :beetle:

#1307 Port changelog for v10.4.3
  CHANGELOG.md
Labels: skip changelog
