Repository mapbox/mapbox-maps-android, pull requests merged in 2022-03, with the labels that each got.

#1189 Check values while apply settings
  CHANGELOG.md
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser2Test.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettingsBase.kt
Labels: feature :green_apple:

#1195 Apply the last release to check api
  scripts/java-api-check.sh
Labels: skip changelog

#1196 Bump metalava dependencies and update api files.
  extension-style/api/metalava.txt
  gradle/metalava.gradle
  plugin-animation/api/metalava.txt
  plugin-annotation/api/metalava.txt
  plugin-attribution/api/metalava.txt
  plugin-compass/api/metalava.txt
  plugin-gestures/api/metalava.txt
  plugin-locationcomponent/api/metalava.txt
  plugin-logo/api/metalava.txt
  plugin-scalebar/api/metalava.txt
  plugin-viewport/api/metalava.txt
  sdk-base/api/metalava.txt
  sdk/api/metalava.txt
Labels: operations, skip changelog

#1193 Remove WeakRefernce from MapboxMap and Style
  CHANGELOG.md
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: skip changelog

#1190 Append version every release
  scripts/update-android-docs.sh
Labels: skip changelog

#1201 Update doc to link to user location guide.
  app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt
  plugin-locationcomponent/README.md
  plugin-viewport/README.md
Labels: skip changelog, docs :scroll:

#1206 Port Match expression fix
  CHANGELOG.md
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/LiteralExpressionTest.kt
Labels: bug :beetle:

#1202 Reset nativeMap to null in onDestroy
  CHANGELOG.md
  app/src/androidTest/java/com/mapbox/maps/testapp/BaseMapTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/NinePatchImageActivity.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  sdk-base/api/metalava.txt
  sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/androidTest/java/com/mapbox/maps/BaseAnimationMapTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: bug :beetle:

#1216 Refactor checkApi, updateApi gradle tasks for metalava and kotlin compatibility validator.
  .circleci/config.yml
  Makefile
  gradle/track-public-apis.gradle
Labels: operations, skip changelog

#1220 Fix description for checkApi/updateApi gradle tasks.
  gradle/track-public-apis.gradle
Labels: skip changelog

#1215 Bump gl-native to v10.4.1, common to v21.2.0
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1222 Expose `MapboxMap#coordinateBoundsForCameraUnwrapped`.
  CHANGELOG.md
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#1224 Port bump gl-native to v10.4.1, common to v21.2.0.
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1221 Refresh changelog management description in the pr template.
  .github/pull_request_template.md
Labels: skip changelog

#1159 [Android Auto] Refactor gesture detection interface
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/api/metalava.txt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallback.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandler.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandlerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
Labels: skip changelog

#1225 Update changelog.
  CHANGELOG.md
Labels: skip changelog

#1223 Fix PolygonAnnotation and PolylineAnnotation distorted while dragging with 3D terrain
  CHANGELOG.md
  plugin-annotation/api/metalava.txt
  plugin-annotation/api/plugin-annotation.api
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/ConvertUtils.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/ShadowProjection.java
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Labels: bug :beetle:

#1230 Refactor native Map and Style to log error and not throw exception
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SimulateNavigationRouteActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/SpaceStationLocationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/fragment/MapFragment.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/SourceExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleInterface.kt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: skip changelog

#1237 Add missing changelog entry for 3D rendering, update versions in README.
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1236 Update change log for v10.4.0 (#1235)
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1241 Mark style as invalid when new style is loaded and apply it to location component
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPositionManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPositionManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapperTest.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: skip changelog

#1248 Throw specific Mapbox exception when geojson data is mutated
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
Labels: feature :green_apple:

#1250 Bump minimist from 1.2.5 to 1.2.6
  package-lock.json
Labels: skip changelog
