Repository mapbox/mapbox-maps-android, pull requests merged in 2022-10, with the labels that each got.

#1710 fix git version script to include latest tags
  gradle/script-git-version.gradle
Labels: skip changelog

#1719 PR #1716 port to release branch v10.9
  CHANGELOG.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/ScaleBarActivity.kt
  app/src/main/res/layout/activity_scale_bar.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
Labels: bug :beetle:

#1725 [ci] Make release branch name matching more strict. [MAPSAND-509]
  .circleci/config.yml
Labels: skip changelog

#1708 MAPSAND-481 adding widget does not refresh map view
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Labels: bug :beetle:

#1706 [Android Auto] Make compatible with v10.5+ versions of maps
  android-auto-app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/CHANGELOG.md
  extension-androidauto/build.gradle.kts
Labels: android auto

#1730 Port add widget fix
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Labels: bug :beetle:

#1728 Scale bar: avoid text overlapping and avoid rendering unless needed
  CHANGELOG.md
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
Labels: bug :beetle:

#1732 PR #1728 port to release branch
  CHANGELOG.md
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
Labels: bug :beetle:

#1729 Bump gl-native to v10.9.0-rc.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1707 Skip checks for changelog branches
  .circleci/config.yml
Labels: skip changelog

#1744 Fix view annotations triggering excessive onMeasure [MAPSAND-516]
  CHANGELOG.md
  sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerAddTest.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerZOrderingTest.kt
Labels: bug :beetle:

#1747 Fix typo location component and README
  metalava/README.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
Labels: skip changelog

#1750 Increase Gradle JVM max memory to 8G and use parallel GC
  gradle.properties
Labels: skip changelog

#1754 Use xlarge machine for `check-gradle-dependencies` job
  .circleci/config.yml
Labels: operations, skip changelog

#1742 Add Mapbox snapshot Maven repository configuration
  .circleci/config.yml
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
Labels: operations, skip changelog

#1755 Replace device that is missing on firebase.
  .circleci/config.yml
Labels: skip changelog

#1756 Use daemons in CI
  .circleci/config.yml
Labels: operations, skip changelog

#1726 [docs] link default property to style property getter/setter docs.
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
Labels: skip changelog

#1758 [Port] default property docs link
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
Labels: skip changelog

#1759 [port] gradle dependency checker
  .circleci/config.yml
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  compose-app/build.gradle.kts
  extension-androidauto/build.gradle.kts
  extension-localization/build.gradle.kts
  extension-style-app/build.gradle.kts
  extension-style/build.gradle.kts
  gradle/dependency-updates.gradle
  mapbox-lint/build.gradle
  module-telemetry/build.gradle.kts
  plugin-animation/build.gradle.kts
  plugin-annotation/build.gradle.kts
  plugin-attribution/build.gradle.kts
  plugin-compass/build.gradle.kts
  plugin-gestures/build.gradle.kts
  plugin-lifecycle/build.gradle.kts
  plugin-locationcomponent/build.gradle.kts
  plugin-logo/build.gradle.kts
  plugin-overlay/build.gradle.kts
  plugin-scalebar/build.gradle.kts
  plugin-viewport/build.gradle.kts
  scripts/merge-gradle-dependency-output.py
  sdk-base/build.gradle.kts
  sdk/build.gradle.kts
Labels: skip changelog

#1771 Changed job `verify-api-revapi` to use Large machine in CI
  .circleci/config.yml
Labels: operations, skip changelog

#1749 Fix revapi release check
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
Labels: skip changelog

#1740 Fix revapi release branch
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
Labels: skip changelog
