Repository mapbox/mapbox-maps-android, pull requests merged in 2022-02, with the labels that each got.

#1105 [deps] Bump gl-native to v10.3.0, common to v21.1.0
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1068 Refactor scheduling events in render thread
  CHANGELOG.md
  app/src/androidTest/java/com/mapbox/maps/testapp/integration/surface/SurfaceViewReopenTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/RenderTest.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/EventType.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RenderEvent.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RenderHandlerThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/RenderHandlerThreadTest.kt
Labels: bug :beetle:

#1119 Improve api-check scripts to show more granular breaking changes.
  .gitignore
  Makefile
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
Labels: operations, skip changelog

#1115 Revert "Add LocationCompassEngine for location component (#970)"
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserDefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserTest.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/res/layout/activity_location_component.xml
  app/src/main/res/layout/generated_test_locationcomponent.xml
  app/src/main/res/menu/menu_location_component.xml
  app/src/main/res/values/strings.xml
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngine.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngineTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParserTest.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
Labels: bug :beetle:

#1112 Don't call initialize twice when getStyle callback fires several times.
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: bug :beetle:

#1126 [viewport] Optimise viewport Java APIs and add validation.
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportStatusChangeReason.kt
Labels: skip changelog

#1116 [Dependencies] Bump gl-native to v10.3.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1124 [ci] add support for invoking internal CI with a datetime
  scripts/ci-circleci-start-pipeline.py
Labels: operations, skip changelog

#1016 Add accuracy radius support for LocationComponent
  CHANGELOG.md
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParser2DefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParser2Test.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/res/layout/generated_test_locationcomponent.xml
  app/src/main/res/menu/menu_location_component.xml
  app/src/main/res/values/strings.xml
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAccuracyRadiusAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser2.kt
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  plugin-locationcomponent/src/main/res/values/colors.xml
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAccuracyRadiusAnimatorTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser2Test.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationConsumer2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/OnIndicatorAccuracyRadiusChangedListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface2.kt
Labels: feature :green_apple:

#1132 Rename view annotation activity using point annotation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationWithPointAnnotationActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#1133 v10.3 port: Rename view annotation activity using point annotation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationWithPointAnnotationActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#1123 Add plugins version
  CHANGELOG.md
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  sdk/build.gradle.kts
Labels: dependencies

#1114 Split callbacks originating on getStyle and loadStyle requests.
  CHANGELOG.md
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapStyleStateDelegate.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: bug :beetle:

#1134 [Deps] Bump gl-native to v10.3.2
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1139 [ci] rename docs CI invoke script to internal release pipeline
  .circleci/config.yml
  scripts/start-internal-release-pipeline.py
Labels: operations, skip changelog

#1142 [viewport] Refinements to public API documentation.
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportExt.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/CompletionListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatus.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatusObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/DefaultViewportTransitionOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateBearing.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportStateDataObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/ViewportTransition.kt
Labels: skip changelog, docs :scroll:

#1146 Port viewport API documentation refinements.
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportExt.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/CompletionListener.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatus.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatusObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/DefaultViewportTransitionOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateBearing.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportStateDataObserver.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransition.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/ViewportTransition.kt
Labels: skip changelog, docs :scroll:

#1120 Integrate Kotlin binary compatibility validator.
  .circleci/config.yml
  .github/pull_request_template.md
  .gitignore
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/api/extension-androidauto.api
  extension-localization/api/extension-localization.api
  extension-style/api/extension-style.api
  mapbox-lint/api/mapbox-lint.api
  module-telemetry/api/module-telemetry.api
  plugin-animation/api/plugin-animation.api
  plugin-annotation/api/plugin-annotation.api
  plugin-attribution/api/plugin-attribution.api
  plugin-compass/api/plugin-compass.api
  plugin-gestures/api/plugin-gestures.api
  plugin-lifecycle/api/plugin-lifecycle.api
  plugin-locationcomponent/api/plugin-locationcomponent.api
  plugin-logo/api/plugin-logo.api
  plugin-overlay/api/plugin-overlay.api
  plugin-scalebar/api/plugin-scalebar.api
  plugin-viewport/api/plugin-viewport.api
  sdk-base/api/sdk-base.api
  sdk/api/sdk.api
Labels: operations, skip changelog

#1036 Custom widget render
  CHANGELOG.md
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapSession.kt
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CompassWidget.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/LogoWidget.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarUtils.kt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
  sdk/src/main/java/com/mapbox/maps/renderer/gl/GlUtils.kt
  sdk/src/main/java/com/mapbox/maps/renderer/gl/TextureRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidgetRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/Widget.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/WidgetPosition.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/WidgetRenderer.kt
  sdk/src/test/java/com/mapbox/TestUtils.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: feature :green_apple:

#1049 Fix erroneous comment
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
Labels: skip changelog, docs :scroll:

#1004 Update android auto extension
  android-auto-app/build.gradle.kts
  android-auto-app/src/main/AndroidManifest.xml
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarJavaInterfaceChecker.java
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapShowcase.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapWidgets.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapSession.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  android-auto-app/src/main/res/values/dimens.xml
  android-auto-app/src/main/res/xml/automotive_app_desc.xml
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/README.md
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/build.gradle.kts
  extension-androidauto/src/main/AndroidManifest.xml
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallback.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapSurfaceProvider.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSurface.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarUtils.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/CompassWidget.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/LogoWidget.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallbackTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/testing/ShadowLogger.java
Labels: skip changelog, feature :green_apple:

#1131 Add LocationCompassEngine for location component
  CHANGELOG.md
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParser2DefaultValueTest.kt
  app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParser2Test.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/res/layout/activity_location_component.xml
  app/src/main/res/layout/generated_test_locationcomponent.xml
  app/src/main/res/menu/menu_location_component.xml
  app/src/main/res/values/strings.xml
  plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/generated/AttributionAttributeParserTest.kt
  plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/generated/CompassAttributeParserTest.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt
  plugin-locationcomponent/README.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngine.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAccuracyRadiusAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckBearingAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimator.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser2.kt
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngineTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser2Test.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParserTest.kt
  plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/generated/LogoAttributeParserTest.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParserTest.kt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase2.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface2.kt
Labels: feature :green_apple:

#1162 Update the generated style docs
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
Labels: skip changelog

#1118 Bump gradle-version, dependencies, support JDK 11
  .gitignore
  CHANGELOG.md
  DEVELOPING.md
  LICENSE.md
  android-auto-app/build.gradle.kts
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-androidauto/build.gradle.kts
  extension-localization/build.gradle.kts
  extension-style-app/build.gradle.kts
  extension-style-app/src/main/AndroidManifest.xml
  extension-style/api/extension-style.api
  extension-style/build.gradle.kts
  gradle.properties
  gradle/jacoco.gradle
  gradle/lint.gradle
  gradle/sdk-registry.gradle
  gradle/wrapper/gradle-wrapper.properties
  module-telemetry/build.gradle.kts
  plugin-animation/build.gradle.kts
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  plugin-annotation/build.gradle.kts
  plugin-attribution/build.gradle.kts
  plugin-compass/build.gradle.kts
  plugin-gestures/build.gradle.kts
  plugin-lifecycle/build.gradle.kts
  plugin-locationcomponent/build.gradle.kts
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-logo/build.gradle.kts
  plugin-overlay/build.gradle.kts
  plugin-scalebar/build.gradle.kts
  plugin-viewport/build.gradle.kts
  sdk-base/build.gradle.kts
  sdk/api/sdk.api
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/FontUtils.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/WidgetPosition.kt
Labels: dependencies

#1093 Fix memory leak in location component.
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
Labels: bug :beetle:

#1160 Bump gl-native to 10.4.0-beta.1, mapbox-common to v21.2.0-beta.1
  CHANGELOG.md
  LICENSE.md
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-style-app/build.gradle.kts
  sdk/api/sdk.api
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: dependencies

#1165 Add new methods to View Annotation API
  CHANGELOG.md
  sdk/api/sdk.api
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/OnViewAnnotationUpdatedListener.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
  sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationVisibility.kt
  sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Labels: feature :green_apple:

#855 Apply RegistryPublish in release job
  .circleci/config.yml
Labels: skip changelog

#1166 InfoWindow using view annotations example
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/InfoWindowActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/Marker.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
  app/src/main/res/drawable/ic_legacy_callout.xml
  app/src/main/res/layout/item_legacy_callout_view.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#1144 Fix bearing of the puck being reset on settings change.
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: skip changelog

#1172 Pass application context.
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngine.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngineTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
Labels: bug :beetle:

#1175 [Deps] Bump gl native 10.4.0 beta.2
  .circleci/config.yml
  CHANGELOG.md
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  extension-style-app/build.gradle.kts
  sdk/build.gradle.kts
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
Labels: dependencies

#1174 Add map function to apply style transition during style load
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/CircleLayerClusteringActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallbackTest.kt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: feature :green_apple:

#1178 Fix custom widget metalava incompatibility
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/renderer/widget/Widget.kt
Labels: skip changelog

#1179 Update changelog and readme for 10.4.0-beta.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1184 Update dokka syntax to fix build.
  sdk/build.gradle.kts
Labels: skip changelog

#1180 Use pixel3 to fix instrumentation tests flaky device
  .circleci/config.yml
Labels: skip changelog

#1183 Change CopyOnWriteArrayList to CopyOnWriteArraySet in the sdk to hold listeners.
  CHANGELOG.md
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
Labels: bug :beetle:

#1187 Port of #1183 to v10.4
  CHANGELOG.md
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
Labels: bug :beetle:

#1167 Update and integrate metalava to the project.
  .circleci/config.yml
  .github/pull_request_template.md
  DEVELOPING.md
  Makefile
  extension-androidauto/api/metalava.txt
  extension-localization/api/metalava.txt
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  gradle/track-public-apis.gradle
  metalava/README.md
  metalava/metalava.jar
  metalava/update.sh
  module-telemetry/api/metalava.txt
  plugin-animation/api/metalava.txt
  plugin-annotation/api/metalava.txt
  plugin-attribution/api/metalava.txt
  plugin-compass/api/metalava.txt
  plugin-gestures/api/metalava.txt
  plugin-lifecycle/api/metalava.txt
  plugin-locationcomponent/api/metalava.txt
  plugin-logo/api/metalava.txt
  plugin-overlay/api/metalava.txt
  plugin-scalebar/api/metalava.txt
  plugin-viewport/api/metalava.txt
  sdk-base/api/metalava.txt
  sdk/api/metalava.txt
Labels: operations, skip changelog

#1191 [port] Port ci changes to fix instrumentation tests device (#1180)
  .circleci/config.yml
Labels: skip changelog
