Repository mapbox/mapbox-maps-android, pull requests merged in 2022-07, with the labels that each got.

#1472 Update robo test devices MAPSAND-268
  .circleci/config.yml
Labels: skip changelog, testing :100:

#1488 adapt sdk to android 13 MAPSMBL-120
  LICENSE.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/camera/CameraPredefinedAnimatorsActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/globe/SpinningGlobeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/MovingIconWithTrailingLineActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
  buildSrc/src/main/kotlin/Project.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
Labels: skip changelog

#1491 Add third party vector source example
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/style/ThirdPartyVectorSourceActivity.kt
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#1509 [Android Auto] Fix android automotive surface recreation issue
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/SearchScreen.kt
  extension-androidauto/CHANGELOG.md
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
  scripts/check-changelog.sh
Labels: android auto

#1473 update release tag MAPSAND-79
  .circleci/config.yml
  DEVELOPING.md
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
  scripts/update-android-docs.sh
Labels: skip changelog

#1524 Add Maps SDK iOS team as the code owner of the public api files.
  .github/CODEOWNERS
Labels: skip changelog

#1523 Add docs about behaviour when globe projection is not supported
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
Labels: skip changelog

#1526 V10.7 port: improve fallback of terrian globe rendering failures
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
Labels: skip changelog

#1520 Add COMMIT_SHA to the snapshot name.
  .circleci/config.yml
Labels: skip changelog

#1534 PR #1527 port to release branch
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#1532 Fix weird crash in StyleObserver
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: bug :beetle:

#1538 Fix edge cases for renderer that could result in map not rendered
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: bug :beetle:

#1542 PR #1532 port to release branch
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: bug :beetle:

#1489 [camera] update api reference docs to include not supported for globe
  sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: skip changelog

#1543 Bump gl-native to 10.7.0, common to 22.1.0
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: dependencies

#1546 V10.7 port: bump gl-native to 10.7.0, common to 22.1.0
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: dependencies
