Repository mapbox/mapbox-maps-android, pull requests merged in 2022-12, with the labels that each got.

#1877 Introduce MapTelemetry.getUserTelemetryRequestState API - MAPSAND-645
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/module/MapTelemetry.java
Labels: feature :green_apple:

#1864 MAPSAND-523 widgets dont update for given scenarios
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceActivity.kt
  app/src/main/res/values/example_descriptions.xml
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidgetRenderer.kt
Labels: bug :beetle:

#1880 MAPSAND-650 fix REGISTRY_EXCLUDE_FROM_ROOT_PROEJCT typo
  extension-androidauto/gradle.properties
  gradle/artifact-settings.gradle
Labels: skip changelog

#1858 [testapp] fix example app build for playstore publish
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  gradle/script-git-version.gradle
Labels: skip changelog

#1884 [port] fix for playstore publish (#1858)
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  gradle/script-git-version.gradle
Labels: skip changelog

#1881 Fix displaying MapView in Android Studio Layout Preview
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapView.kt
Labels: bug :beetle:

#1885 PR #1881 port to release branch
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapView.kt
Labels: bug :beetle:

#1876 Improve performance by setting geojson data directly
  .circleci/config.yml
  buildSrc/src/main/kotlin/Project.kt
  extension-style/api/extension-style.api
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: skip changelog

#1883 [ci] Ignore API changes for internal WidgetRenderer and BitmapWidgetRenderer.
  scripts/java-api-check.json
Labels: skip changelog

#1890 update license file
  LICENSE.md
Labels: skip changelog

#1891 [deps] Bump gl-native to v10.10.0, common to v23.2.0.
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1888 PR #1876 port to release branch
  .circleci/config.yml
  extension-style/api/extension-style.api
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
  plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: skip changelog, DO NOT MERGE

#1859 Revert location engine packages.
  app/src/main/java/com/mapbox/maps/testapp/utils/LocationPermissionHelper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
Labels: skip changelog

#1896 PR #1895 port to release branch
  .circleci/config.yml
Labels: operations, skip changelog

#1612 bump gradle to 7.5.1
  gradle/wrapper/gradle-wrapper.properties
  scripts/checksum.sh
Labels: skip changelog

#1731 [app] add example on animating a view annotation along a routeline
  app/src/main/AndroidManifest.xml
  app/src/main/assets/sf_airport_route.geojson
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationAnimationActivity.kt
  app/src/main/res/layout/activity_mapview.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1905 Added example for secondary display using Presentation
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/SecondaryDisplayPresentationActivity.kt
  app/src/main/res/layout/activity_secondary_display_presentation.xml
  app/src/main/res/layout/item_display_info.xml
Labels: skip changelog

#1911 [ci] continously verify if permission changes
  .circleci/config.yml
  Makefile
  app/permission.json
  scripts/check-permissions.py
Labels: operations, skip changelog

#1912 [tests] patch flaky tests
  sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/LifecycleTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/StyleProjectionTest.kt
  sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
Labels: skip changelog

#1916 [ci] optimize device configuration for firebase testlab
  .circleci/config.yml
  scripts/ci-weekly-trigger.py
Labels: skip changelog

#1909 Skip camera updates in Animation if it's already applied
  CHANGELOG.md
  plugin-animation/api/metalava.txt
  plugin-animation/api/plugin-animation.api
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraOptionsUtils.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsChangeListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
  sdk-base/api/metalava.txt
  sdk-base/src/main/java/com/mapbox/maps/plugin/MapCameraPlugin.kt
  sdk-base/src/main/java/com/mapbox/maps/util/MathUtils.kt
Labels: feature :green_apple:
