Repository mapbox/mapbox-maps-android, pull requests merged in 2022-09, with the labels that each got.

#1639 fix boolean flag parser
  scripts/ci-circleci-start-pipeline.py
Labels: skip changelog

#1635 MAPSAND-221 setting puck bearing enabled to false does not reset bearing
  CHANGELOG.md
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Labels: bug :beetle:

#1621 Notify about release branch update MAPSMBL-152
  .circleci/config.yml
  extension-localization/gradle.properties
  plugin-lifecycle/gradle.properties
  plugin-overlay/gradle.properties
  scripts/ci-circleci-start-pipeline.py
Labels: skip changelog

#1622 MAPSAND-379 Style getter extension functions do not save property values
  CHANGELOG.md
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/BackgroundLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/CircleLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillExtrusionLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/HeatmapLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/HillshadeLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LineLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/RasterLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/SkyLayerTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/SymbolLayerTest.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
Labels: bug :beetle:

#1658 Fix incorrect MapView dimensions on background orientation change
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Labels: bug :beetle:

#1660 [ci] remove trigger to mobile metrics v1
  .circleci/config.yml
  scripts/mobile-metrics-start-pipeline.py
Labels: skip changelog

#1638 Introduce runtime config to run Mapbox animators on background thread
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarAnimationThreadController.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapSession.kt
  extension-androidauto/README.md
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/HighLevelAnimatorSet.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/threading/AnimationThreadController.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: skip changelog

#1624 [v10.9] revert setCamera exception fix #652
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
Labels: skip changelog

#1676 Updated docs fill extrusion layer
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
Labels: skip changelog, docs :scroll:

#1651 MAPSMBL-159 android auto wrong bitmap widget position after calling update bitmap with a bitmap that has different size
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidgetRenderer.kt
Labels: bug :beetle:

#1659 Feature: Location puck opacity
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
  app/src/main/res/menu/menu_location_component.xml
  app/src/main/res/values/strings.xml
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LocationIndicatorLayerTest.kt
  extension-style/api/extension-style.api
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
Labels: feature :green_apple:

#1662 Added `pitch` and `distance-from-center` expressions support
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
  extension-style/api/extension-style.api
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/dsl/generated/ExpressionDsl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt
Labels: feature :green_apple:

#1681 Throw exception when constructing Value with NaN or infinite numbers.
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/properties/PropertyValue.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt
Labels: bug :beetle:

#1648 [Android Auto] Add stable area changed callback
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  extension-androidauto/CHANGELOG.md
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/api/metalava.txt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.java
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.java
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
Labels: android auto

#1683 [Android Auto] Allow for downstream upgrades
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  extension-androidauto/CHANGELOG.md
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/api/metalava.txt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
Labels: android auto

#1688 [Android Auto] Add changelog for 0.3.0
  extension-androidauto/CHANGELOG.md
  extension-androidauto/gradle.properties
Labels: skip changelog, android auto

#1691 Soften log message when using outdated map / style objects
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: skip changelog

#1696 Bump common sdk to v23.1.0-beta.2.
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1637 add gradle dependency checker MAPSAND-341
  .circleci/config.yml
  android-auto-app/build.gradle.kts
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  compose-app/build.gradle.kts
  extension-androidauto/build.gradle.kts
  extension-localization/build.gradle.kts
  extension-style-app/build.gradle.kts
  extension-style/build.gradle.kts
  gradle/dependency-updates.gradle
  mapbox-lint/build.gradle
  module-telemetry/build.gradle.kts
  plugin-animation/build.gradle.kts
  plugin-annotation/build.gradle.kts
  plugin-attribution/build.gradle.kts
  plugin-compass/build.gradle.kts
  plugin-gestures/build.gradle.kts
  plugin-lifecycle/build.gradle.kts
  plugin-locationcomponent/build.gradle.kts
  plugin-logo/build.gradle.kts
  plugin-overlay/build.gradle.kts
  plugin-scalebar/build.gradle.kts
  plugin-viewport/build.gradle.kts
  scripts/merge-gradle-dependency-output.py
  sdk-base/build.gradle.kts
  sdk/build.gradle.kts
Labels: skip changelog
