Repository mapbox/mapbox-maps-android, pull requests merged in 2022-05, with the labels that each got.

#1311 [Docs] use internal branch to publish docs
  .circleci/config.yml
Labels: skip changelog

#1323 [deps] Bump Android base library to v0.8.0, to support incremental annotation processing.
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1324 Fix geojson missing updates with persistent layer after style change
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: bug :beetle:

#1328 V10.5 port: Fix persistent layer update style change
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: bug :beetle:

#1337 Update metalava API files
  extension-style/api/metalava.txt
  sdk-base/api/metalava.txt
  sdk/api/metalava.txt
Labels: skip changelog

#1327 Use non-deprecated common logger
  CHANGELOG.md
  sdk-base/src/main/java/com/mapbox/common/MapboxCommonLogger.kt
  sdk-base/src/main/java/com/mapbox/maps/MapboxLogger.kt
Labels: feature :green_apple:

#1338 Expose camera animators factory methods
  CHANGELOG.md
  plugin-animation/api/metalava.txt
  plugin-animation/api/plugin-animation.api
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
Labels: feature :green_apple:

#1336 Remove padding while calculating unitBarWidth; invalidateScaleBar while applySettings
  CHANGELOG.md
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
Labels: bug :beetle:

#1347 optimize verify internal CI task
  .circleci/config.yml
Labels: skip changelog

#1351 Bump gl-native to v10.6.0-beta.1, common to 22.0.0-beta.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  sdk-base/build.gradle.kts
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Labels: dependencies

#1344 Add style atmosphere support
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/Terrain3DShowcaseActivity.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/atmosphere/generated/AtmosphereTest.kt
  extension-style/api/extension-style.api
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/TypeDSLs.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
  sdk-base/api/metalava.txt
  sdk-base/api/sdk-base.api
  sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: feature :green_apple:

#1359 [Deps] bump gl-native v10.6.0-beta.3
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1357 [provider] rework map providers
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapProvider.kt
  sdk/src/main/java/com/mapbox/maps/NativeMapProvider.java
Labels: skip changelog

#1364 Fix crash due to invalid focal point when panning the map
  CHANGELOG.md
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: bug :beetle:

#1368 Add static method to validate if 3D terrain is supported
  CHANGELOG.md
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
Labels: feature :green_apple:

#1365 [docs] update dokka to 1.5.31 and remove jcenter
  build.gradle.kts
  buildSrc/src/main/kotlin/Project.kt
  compose/build.gradle
  extension-androidauto/build.gradle.kts
  extension-localization/build.gradle.kts
  extension-style/build.gradle.kts
  module-telemetry/build.gradle.kts
  plugin-animation/build.gradle.kts
  plugin-annotation/build.gradle.kts
  plugin-attribution/build.gradle.kts
  plugin-compass/build.gradle.kts
  plugin-gestures/build.gradle.kts
  plugin-lifecycle/build.gradle.kts
  plugin-locationcomponent/build.gradle.kts
  plugin-logo/build.gradle.kts
  plugin-overlay/build.gradle.kts
  plugin-scalebar/build.gradle.kts
  plugin-viewport/build.gradle.kts
  sdk-base/build.gradle.kts
  sdk/build.gradle.kts
  settings.gradle.kts
Labels: skip changelog, docs :scroll:

#1355 Get the correct last stable release name for revapi
  scripts/java-api-check-all.sh
  scripts/java-api-check.sh
Labels: skip changelog

#1372 Prepare for v10.6.0-beta.1 release
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  gradle.properties
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
  sdk/api/metalava.txt
Labels: skip changelog

#1379 Fix back button not working in some activities.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/camera/RestrictBoundsActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/localization/LocalizationActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
Labels: skip changelog

#1383 [docs] Improve style extension documentation.
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
Labels: docs :scroll:

#1385 Port documentation improvements to Style API
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
Labels: docs :scroll:

#1386 fix checkNativeMap function call for cameraForCoordinates
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Labels: bug :beetle:, skip changelog

#1393 Fix compass is not showing in "edge-to-edge" mode
  CHANGELOG.md
  plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt
Labels: bug :beetle:
