Repository mapbox/mapbox-maps-android, pull requests merged in 2022-06, with the labels that each got.

#1396 Bump gl-native to 10.6.0-rc.1, common to 22.0.0-rc.2
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
  sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Labels: dependencies

#1404 Clean up changelog after 10.6.0-rc.1
  CHANGELOG.md
Labels: skip changelog

#1407 Use `orientation` model source property to update the 3D puck's bearing.
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/sources/TileSet.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
  plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
  plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapperTest.kt
Labels: performance :zap:

#1378 Load sprites and sources style extensions earlier during onStyleLoad.
  CHANGELOG.md
  sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
  sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
  sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
  sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
Labels: feature :green_apple:

#1416 Fix issue when tasks are skipped if surface is recreated - MAPSAND-177.
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/renderer/EventType.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RenderEvent.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RenderHandlerThread.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/RenderHandlerThreadTest.kt
Labels: bug :beetle:

#1435 Update docs for v10.6.0 release.
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1439 Update docs for v10.6.0 release. (#1435)
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1433 [lint] remove unused resources and fix some docs MAPSAND-93
  plugin-attribution/src/main/res/values/strings.xml
  plugin-locationcomponent/src/main/res/values/dimens.xml
  plugin-locationcomponent/src/main/res/values/strings.xml
  plugin-logo/src/main/res/values/strings.xml
  sdk-base/src/main/res/values/strings.xml
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/main/java/com/mapbox/maps/attribution/AttributionParser.kt
  sdk/src/main/res/values/strings.xml
Labels: skip changelog

#1427 Introduce API to control errors during renderer creation
  CHANGELOG.md
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/build.gradle.kts
  sdk/src/androidTest/java/com/mapbox/maps/renderer/egl/RendererSetupTest.kt
  sdk/src/main/java/com/mapbox/maps/MapControllable.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RendererError.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RendererSetupErrorListener.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
  sdk/src/test/java/com/mapbox/maps/EqualsHashCodeTest.kt
  sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
Labels: feature :green_apple:

#1452 Add missing API doc for eglErrorCode.
  sdk/src/main/java/com/mapbox/maps/renderer/RendererError.kt
Labels: skip changelog

#1453 Fix verify-docs CI scripts, increase CI container size for flaky bots.
  .circleci/config.yml
  scripts/kdoc-validate.sh
Labels: operations, skip changelog

#1451 Add missing transition properties for atmosphere and terrain
  CHANGELOG.md
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/atmosphere/generated/AtmosphereTest.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/terrain/generated/TerrainTest.kt
  extension-style/api/extension-style.api
  extension-style/api/metalava.txt
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt
Labels: feature :green_apple:

#1448 Align globe examples with gl js
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/mapbox/maps/testapp/examples/GlobeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/camera/AnimateMapCameraActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/camera/LowLevelCameraAnimatorActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/globe/GlobeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/globe/GlobeFlyToActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/globe/HeatmapLayerGlobeActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/globe/SpinningGlobeActivity.kt
  app/src/main/res/layout/activity_camera_animate.xml
  app/src/main/res/layout/activity_globe_view.xml
  app/src/main/res/values/example_categories.xml
  app/src/main/res/values/example_descriptions.xml
  app/src/main/res/values/example_titles.xml
Labels: skip changelog

#1462 Bump gl-native to 10.7.0-beta.1, common to 22.1.0-beta.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1447 [shadow-api] Add experimental shadow api MAPSAND-165
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt
  app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
  app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/FillExtrusionActivity.kt
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/light/generated/LightTest.kt
  extension-style/api/extension-style.api
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
Labels: feature :green_apple:

#1464 Update docs for v10.7.0-beta.1 release
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  gradle.properties
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: docs :scroll:

#1471 Fix modelIdAsExpression instrumentation test.
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/ModelLayerTest.kt
Labels: testing :100:

#1469 [codegen] update annotation test to fix codegen job
  app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
Labels: bug :beetle:, skip changelog
