Repository mapbox/mapbox-maps-android, pull requests merged in 2022-08, with the labels that each got.

#1552 Fix onAnnotationDragStarted event is still fired when annotation is not draggable - MAPSAND-356
  CHANGELOG.md
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
Labels: bug :beetle:

#1555 downgrade androidx core to 1.7.0
  LICENSE.md
  buildSrc/src/main/kotlin/Project.kt
  extension-style/api/metalava.txt
Labels: skip changelog

#1553 fix render thread tests MAPSAND-337
  .circleci/config.yml
  buildSrc/src/main/kotlin/Project.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Labels: skip changelog, testing :100:

#1560 Fix camera flying away when pitching
  CHANGELOG.md
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
  plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
Labels: bug :beetle:

#1564 Set the right path for PuckAnimators in api check config
  scripts/java-api-check.json
Labels: skip changelog

#1539 [Android Auto] Release changelog 0.2.0
  extension-androidauto/CHANGELOG.md
Labels: skip changelog, android auto

#1565 Fix the git release tag matching for CI/CD.
  .circleci/config.yml
Labels: skip changelog

#1568 Bump gl-native to v10.8.0-beta.1, common to v23.0.0-beta.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1541 [viewport] use shortest path for viewport bearing transition MAPSAND-188
  CHANGELOG.md
  plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
Labels: bug :beetle:

#1477 Fix setting max fps and fps count for renderer
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
  sdk/src/main/java/com/mapbox/maps/MapController.kt
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/main/java/com/mapbox/maps/MapView.kt
  sdk/src/main/java/com/mapbox/maps/renderer/FpsManager.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
  sdk/src/main/java/com/mapbox/maps/renderer/RenderHandlerThread.kt
  sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/FpsManagerTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
  sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Labels: bug :beetle:

#1571 Update metalava file with new param name
  sdk/api/metalava.txt
Labels: skip changelog

#1572 [docs] update location component docs
  plugin-locationcomponent/src/main/res-public/values/public.xml
  plugin-locationcomponent/src/main/res/values/attrs.xml
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
  sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
Labels: docs :scroll:

#1573 Fix style getters for terrain, light and atmosphere resetting properties
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
  extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/TerrainExt.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
  extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt
Labels: bug :beetle:

#1574 Bump gl-native 10.8.0-beta.2
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: dependencies

#1575 Fix MapSurface#surfaceChanged to update dimensions for plugins
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
Labels: bug :beetle:

#1576 Update the generated doc to match style spec.
  CHANGELOG.md
  extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
  plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
Labels: skip changelog

#1577 [ci] fix snapshot version name MAPSAND-377
  .circleci/config.yml
Labels: bug :beetle:, skip changelog

#1578 Update changelog for 10.8.0-beta.1
  CHANGELOG.md
  extension-localization/README.md
  extension-style/README.md
  gradle.properties
  plugin-animation/README.md
  plugin-annotation/README.md
  plugin-attribution/README.md
  plugin-compass/README.md
  plugin-gestures/README.md
  plugin-lifecycle/README.md
  plugin-locationcomponent/README.md
  plugin-logo/README.md
  plugin-overlay/README.md
  plugin-scalebar/README.md
  plugin-viewport/README.md
Labels: skip changelog

#1580 [ci ] Fix ci to run on correct internal branch
  .circleci/config.yml
Labels: bug :beetle:, skip changelog

#1581 fix e2e script path
  .circleci/config.yml
  scripts/ci-e2e-job-trigger-checker.sh
Labels: skip changelog

#1590 Fix the upload script to avoid parallel execution.
  Makefile
Labels: skip changelog

#1589 Try recreate EGL surface when it throws exception
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
Labels: bug :beetle:

#1592 V10.8 port: Try recreate EGL surface when it throws exception
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
  sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
Labels: bug :beetle:

#1587 MAPSAND-378 create unit tests for map surface class
  sdk/build.gradle.kts
  sdk/src/main/java/com/mapbox/maps/MapSurface.kt
  sdk/src/test/java/com/mapbox/maps/MapSurfaceTest.kt
Labels: testing :100:

#1591 Fix MapboxMap extension plugin functions throwing exceptions
  CHANGELOG.md
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#1595 V10.8 port: Fix MapboxMap extension plugin functions throwing exceptions
  CHANGELOG.md
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
  plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
  sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
  sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Labels: bug :beetle:

#1597 Fix concurrent modification exception when using widgets
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
Labels: bug :beetle:

#1600 V10.8 port: fix concurrent modification exception when using widgets
  CHANGELOG.md
  sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
Labels: bug :beetle:

#1601 Fix permissions for e2e scripts
  .circleci/config.yml
  scripts/ci-e2e-compatibility-start-pipeline.py
  scripts/ci-e2e-job-trigger-checker.sh
Labels: skip changelog

#1602 V10.8 port: fix e2e script permission
  .circleci/config.yml
  scripts/ci-e2e-compatibility-start-pipeline.py
  scripts/ci-e2e-job-trigger-checker.sh
Labels: skip changelog

#1593 Notify private repo about main update [MAPSAND-374]
  .circleci/config.yml
  package.json
Labels: skip changelog

#1606 [Android Auto] Add activity to android auto app
  android-auto-app/build.gradle.kts
  android-auto-app/src/main/AndroidManifest.xml
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/app/MainActivity.kt
  android-auto-app/src/main/res/layout/activity_main.xml
  android-auto-app/src/main/res/values/themes.xml
Labels: skip changelog, android auto

#1611 refactor gradle-cache CI commands
  .circleci/config.yml
Labels: skip changelog

#1613 Fix info window activity example
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
Labels: skip changelog

#1615 v10.8 port: fix info window activity example
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
Labels: skip changelog

#1614 [example] fix inset activity MAPSMBL-156
  app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
Labels: skip changelog

#1619 Bump ejs from 2.7.4 to 3.1.7
  package-lock.json
Labels: skip changelog

#1603 [Android Auto] Allow early initialization
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapSession.kt
  android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
  extension-androidauto/CHANGELOG.md
  extension-androidauto/README.md
  extension-androidauto/api/extension-androidauto.api
  extension-androidauto/api/metalava.txt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallback.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapEx.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapInitializer.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapScreenInstaller.kt
  extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSessionInstaller.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallbackTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapScreenInstallerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSessionInstallerTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
  extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/testing/TestLifecycleOwner.kt
Labels: android auto

#1620 Rs fix scale bar truncated - MAPSAND-305
  CHANGELOG.md
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarConstant.kt
  plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
  plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
  scripts/java-api-check.json
Labels: bug :beetle:

#1627 Add release date to v10.8.0-rc.1 change log.
  CHANGELOG.md
Labels: skip changelog

#1625 Small improvements on `Style` docs
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: skip changelog

#1616 Use on draw listener in view annotation manager for more granular control
  CHANGELOG.md
  app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
  sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
  sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
Labels: bug :beetle:

#1633 Small format fix to DEVELOPING.md
  DEVELOPING.md
Labels: skip changelog

#1631 Add release date to changelog. (#1627)
  CHANGELOG.md
Labels: skip changelog

#1632 Deprecate gesture settings increaseRotateThresholdWhenPinchingToZoom
  CHANGELOG.md
  plugin-gestures/src/main/res-public/values/public.xml
  sdk-base/api/metalava.txt
  sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
Labels: feature :green_apple:
