Repository mapbox/mapbox-maps-android, pull requests merged in 2023-01, with the labels that each got.

#1928 Make 'Cluster points within a layer' example code compatible with GL JS / iOS
  app/src/main/java/com/mapbox/maps/testapp/examples/CircleLayerClusteringActivity.kt
Labels: skip changelog

#1934 Bump GL Native to 10.11.0-beta.1 and Common to 23.3.0-beta.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
  sdk/api/metalava.txt
  sdk/api/sdk.api
  sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
  sdk/src/main/java/com/mapbox/maps/Style.kt
Labels: dependencies

#1950 Remove unnecessary SSH key fingerprint from CircleCI config
  .circleci/config.yml
Labels: operations, skip changelog, run_e2e

#1955 [port] wrap longitude to world bound for flyTo animation. (#1949)
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
  plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
  plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt
Labels: skip changelog

#1957 bump gl native v10.10.1, common to v23.2.2 MAPSAND-745
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1958 remove date for release train
  CHANGELOG.md
Labels: skip changelog

#1959 [port] changelog for 10.10.1
  CHANGELOG.md
Labels: skip changelog

#1918 Create codeql.yml
  .github/workflows/codeql.yml
Labels: skip changelog

#1965 update license file
  LICENSE.md
Labels: skip changelog

#1953 bump gl-native to v10.11.0-rc.1, common to v23.3.0-rc.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1969 [port] changelog 10.11 rc.1
  CHANGELOG.md
  buildSrc/src/main/kotlin/Project.kt
Labels: skip changelog

#1970 fix release title
  CHANGELOG.md
Labels: skip changelog

#1976 Added slack notification when snapshot is published
  .circleci/config.yml
Labels: skip changelog

#1982 update license
  LICENSE.md
Labels: skip changelog

#1980 [MAPSAND-716] fix geojson tests
  extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
Labels: skip changelog
